### ISSUE TITLE
Proposal: A super efficient airdrop tool on Kaia

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#1]
Description
- A tool to airdrop KAIA, ERC20 tokens and NFTs. The DApp will have an easy to use frontend.

Bounty track
- [Contribute a free to use DApp onto mainnet](https://dorahacks.io/daobounty/448)

Migrated from old issue:
- https://github.com/klaytn/klaytn-dapp-toolkit/issues/19

**Comment by haxxsniper** [comment]
https://gaslite-ui.vercel.app/

Deployed address on Baobab: https://baobab.klaytnfinder.io/account/0x61684fc62b6a0f1273f69d9fca0e264001a61db6
Deployed address on Cypress: https://klaytnfinder.io/account/0x53a7a12b0a6da201addfe6c3cdcd75df04bba640

UI repo: https://github.com/haxxsniper/gaslite-ui
Contracts repo: https://github.com/haxxsniper/gaslite-drop-contracts

Will be making updates very soon

**Comment by haxxsniper** [comment]
@zxstim just made a massive UI overhaul for the airdrop tool for all the functionalities
https://gaslite-ui.vercel.app/

UI repo: https://github.com/haxxsniper/gaslite-ui
Contracts repo: https://github.com/haxxsniper/gaslite-drop-contracts

**Comment by zxstim** [comment]
definitely looking nicer than before. Let me try and revert.

**Comment by zxstim** [comment]
Works super well. def a great contribution for people to do airdrop campaigns on kaia.

**Comment by zxstim** [comment]
Closed the issue now with the recent PR #21
