### ISSUE TITLE
Proposal: ShitFire - Platform that allows users to shoot Shit NFTs to each other

### ISSUE THREAD

**Issue by SaitamaCoderVN** [kaiachain/kaia-dapp-mono#100]
Description
- Fire Shit Soulbound NFT to any account you want
- Wallet account holders can only clean up NFT shit when paying to clean up trash in the wallet
- When the owner spends money to clean up trash, people who shoot Shit NFT for that owner will receive a a commission

Bounty track
- Dapp on Kaia

**Comment by zxstim** [comment]
i love trolling and memes. Approved with a checkmark ✅

**Comment by SaitamaCoderVN** [comment]
This is ShitFire - Platform that allows users to shoot Shit NFTs to each:
https://shit-fire.vercel.app

This is ShitFire Token address:
- BAOBAB: 0x02dEf6F97a9e097334812836B04066C40cfbCC29
- CYPRESS: 0xC5f65cd573Cf825018C864bEBb3a661bcdDA846a

This is ShitFire NFT address:
- BAOBAB: 0x20339e917b2b68d74F04215Fbd3822442Cd3ED02
- CYPRESS: 0x535B38DE606B10fD5F2D3D8962BEBD47F0Fd63D3

This is contract repo:
https://github.com/SaitamaCoderVN/ShitFire-Contract-Foundary

This is front-end repo:
https://github.com/SaitamaCoderVN/ShitFire

**Comment by zxstim** [comment]
Code is a bit messy but the UI represents the spirit well. Approved for `1200 KLAY` payout.

**Comment by SaitamaCoderVN** [comment]
Updating Version 2: 
- I will clean up the code for this source and contract, research security methods to optimize the security of this contract.
- Designed to add a function to show the list of wallets that received the most shitNFT
- Complete ShitCoin P2P staking and trading functions on the website
