### ISSUE TITLE
Proposal: Dashboard Visualization for Kaia DEXes (CapybaraDEX & Neopin)

### ISSUE THREAD

**Issue by 3ppleA** [kaiachain/kaia-dapp-mono#102]
[Description]
The purpose of this #BUIDL is to provide a robust and interactive dashboard detailing key metrics such as swaps, liquidity pool, staking, total value locked (TVL), farming, and more for decentralized exchanges including CapybaraDEX and Neopin built on Kaia chain.

CapybaraDEX- the first launchpad and decentralized exchange on Kaia chain. 
Neopin- a one-stop non-custodial permissioned DeFi & TradFi protocol for utilizing your crypto securely.

Bounty track
DeFi

CapybaraDEX: [https://flipsidecrypto.xyz/Sajjadiii/kaia-capybara-qBFN_A](url)
Neopin: [https://flipsidecrypto.xyz/Sajjadiii/kaia-neopin-on-kaia-eIifgx](url)

----
Acknowledgement: I confirm the below address is my bounty payout address.
Payout address: 0x0baa69b3e32d5eae62c8f1a053f23fbdd4670cf7

**Comment by zxstim** [comment]
Approved for `700 KLAY` payout

**Comment by zxstim** [comment]
Closing for payout.
