### ISSUE TITLE
Proposal: Kaia-Oracle-ToolKit

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#103]
Description:

- A Kaia Oracle Integration ToolKit Repository that showcases how to integrate Oracle Platforms and Services supported by kaia into a DApp.
- It demonstrates how to integrate the following Oracle Services:
Orakl for Randomness and for fetching data feeds,
Pyth for fetching $KAIA token Data Feed and 
SupraOracle .
- It contains script file and test cases.
- Lastly, it contains a readme file that expantiates on the integration process for each oracle platform.

Bounty track:

- Developer Tools

**Comment by zxstim** [comment]
Approved to proceed.

**Comment by PaulElisha** [comment]
Here are links to the repository and submission on dorahacks:

https://github.com/PaulElisha/Kaia-Oracle-Toolkit
https://dorahacks.io/buidl/15980
