### ISSUE TITLE
Proposal: Kaia-Precompile-Interaction-Contract-Toolkit

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#104]
Description
- A toolkit that demonstrates the integration of native kaia precompiled contract into a codebase.
- A readme file that explains the integration process for ease-of-use.

Bounty track
- Developer Tools

**Comment by zxstim** [comment]
Approved to proceed.

**Comment by PaulElisha** [comment]
https://dorahacks.io/buidl/16103

https://github.com/PaulElisha/Kaia-Precompile-Toolkit

**Comment by zxstim** [comment]
After careful review, this is ok. `1200 KLAY` payout. You should expand your docs, add deployment scripts, configurations, for extra bounty.

I don't want to see the use of Private Key with foundry any more by the way. Will not pass the submission if i see that.

**Comment by zxstim** [comment]
Closing for payout
