### ISSUE TITLE
Proposal: Airdrop Distribution Contract

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#106]
Description
- A smart contract that can be used for Airdrop distribution.
- It highlights the use of the MerkleProof Library for proof verification
- It shows how to claim airdrop efficiently using MerkleTrees for data storage.

Bounty track
- DeFi

**Comment by zxstim** [comment]
Approved to proceed.

**Comment by PaulElisha** [comment]
Here is a submission link to the repository and the build on dorahacks:

https://github.com/PaulElisha/Kaia-Airdrop-Distribution
https://dorahacks.io/buidl/15975

**Comment by zxstim** [comment]
Approved for `1000 KLAY` payout. Need some docs for others.
