### ISSUE TITLE
Proposal: GMGN engagement tool

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#109]
Description
- An app for various wallet interactions
- Allow wallet to send messages to other wallets on Kaia
- Allow wallet owner to sign text and send to other person as links

Bounty track
- [add the name of the bounty track here]

**Comment by zxstim** [comment]
Approved to proceed.

**Comment by haxxsniper** [comment]
Please find the links here:
https://dorahacks.io/buidl/15990

Repo link: https://github.com/blockcmd/gmgn

App link: https://gmgn.app

**Comment by zxstim** [comment]
Approved for `1500 KLAY` payout. Closing this issue for payout.
