### ISSUE TITLE
Proposal: Update to GMGN engagement tool

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#112]
Reference
- #109 

Description
- Added full wallet creation and support (stored in device Passkeys)
- Re-worked message and sign feature to be compatible with local account
- Super fast onboarding

Bounty track
- Other

**Comment by zxstim** [comment]
Good idea with passkey. Approved to proceed.

**Comment by haxxsniper** [comment]
You can check https://gmgn.app for the update.

Code is here: https://github.com/blockcmd/gmgn
BUIDL: https://dorahacks.io/buidl/15990
