### ISSUE TITLE
Proposal: Meetup online

### ISSUE THREAD

**Issue by tungleanh0902** [kaiachain/kaia-dapp-mono#114]
Description
- An online meetup to introduce Kaia Blockchain. We will discover cutting-edge technologies, engage with industry experts, and explore new opportunities in technology and innovation on 10th September 2024.
- Link: https://lu.ma/88q7m5c8

**Comment by zxstim** [comment]
Approved. I will grant `200 KLAY` for the community. Will assist you with wallet collection later.
