### ISSUE TITLE
Proposal: Sorting Puzzle Blockchain Game On Kaia

### ISSUE THREAD

**Issue by KelvinTrinhSG** [kaiachain/kaia-dapp-mono#115]
Description
- The game is developed with Unity Engine and integrated with Kaia blockchain.
- The game utilizes NFT as in-game items (Token Gate).
- The game uses ERC20 Tokens issued to players to support players during the game and for players to experience the Kaia chain.
- The game has attractive gameplay and beautiful graphics.
- The game is aimed at Play To Relax and Play to Learn.

![Puzzle Game On Kaia](https://github.com/user-attachments/assets/8414fe36-9039-4b36-bc06-b5c1e21ee83b)

Bounty track
- Other

**Comment by zxstim** [comment]
Cool. Approved.

**Comment by KelvinTrinhSG** [comment]
You can check

https://thkien85.itch.io/impostor-puzzle-game-on-kaia

for the update.
I used Unity Engine to create the game.

The game uses 2 smart contracts with the addresses:
ERC721
0xAFBbd54017CAdbe4d9437743F734896018e6A9d6
And
ERC20
0x50Aa1F062AB55925458c23fbc0d7B12FE89bD33a

Code is here: https://github.com/KelvinTrinhSG/Impostor-Puzzle-Game-On-Kaia-Chain
BUIDL: https://dorahacks.io/buidl/16196
Video: https://www.youtube.com/watch?v=_m7U272VBnc

Thanks and best regards,

**Comment by KelvinTrinhSG** [comment]
@zxstim May I ask if we could mark this project clear before I continue to move to the next one?
Thanks.

**Comment by zxstim** [comment]
You don't to wait for this project to be clear before moving on to the next. You can keep proposing new ones.

And yes, thanks for the ping. Keep reminding me if I don't respond within 2 days.

**Comment by KelvinTrinhSG** [comment]
> You don't have to wait for this project to be clear before moving on to the next. You can keep proposing new ones.
> 
> And yes, thanks for the ping. Keep reminding me if I don't respond within 2 days.

@zxstim 
May I ask if I get any rewards or anything?

Thank you.

**Comment by zxstim** [comment]
yes you will. Will take me a day or 2 to review and assign the bounty rewards. I actually missed your submission so didn't check before.

**Comment by zxstim** [comment]
Approved `1500 KLAY` bounty payout. I think the direction for this game could be:
- Token gated experience (so purchase NFT for access)
- Receive tokens for rewards (some form of currencies)

**Comment by zxstim** [comment]
in terms of gameplay, this is not my type of game so I won't comment much. Maybe show me something popular and similar so I can think of some ways to help you grow.

**Comment by zxstim** [comment]
Closing for payout

**Comment by KelvinTrinhSG** [comment]
Thank you so much for your support.
For me, this is also an interesting experience when interacting with the Kaia chain and making new friends. I really appreciate it.
