### ISSUE TITLE
Proposal: [Do you need help with sales and marketing?]

### ISSUE THREAD

**Issue by IsitorViper** [kaiachain/kaia-dapp-mono#123]
Description
- [Hi I would like to join your sales and marketing team/department. I have a natural talent for sales. Is the community on discord? if so please send me a link so that we can move this conversation there. Regards. Isitor]

Bounty track
- [Increased community activity]

**Comment by zxstim** [comment]
the Issue tab is not meant for this.

**Comment by IsitorViper** [comment]
Noted. What is the correct channel to go about this?

**Comment by zxstim** [comment]
https://discord.gg/kaiachain

just engage with the mods there

**Comment by IsitorViper** [comment]
Thanks.
