### ISSUE TITLE
Update: Adopt Kaia SDK and add Fee Delegation to GMGN wallet - GMGN wallet

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#124]
Description
- Switching to using Kaia SDK ethers-ext rather than viem
- Configure fee delegation for for `send` and `message`
- Fixes to improve stability

Reference issue
- #112 

Category
- Other

**Comment by zxstim** [comment]
Great use of Kaia SDK

**Comment by haxxsniper** [comment]
Updated on https://gmgn.app/ now

Code is here: https://github.com/blockcmd/gmgn
BUIDL: https://dorahacks.io/buidl/15990

**Comment by zxstim** [comment]
Sweet. Works super well.

Approved for `1500 KLAY` bounty
