### ISSUE TITLE
Proposal: Weekly coffee meetup

### ISSUE THREAD

**Issue by BeeWireOfficial** [kaiachain/kaia-dapp-mono#125]
Description
- [Build Buddies - Caffeine Sessions is a weekly meetup bringing together tech enthusiasts, developers, and community builders with a focus on blockchain, AI, and web3. It provides a relaxed space for networking, sharing ideas, and exploring potential collaborations. The meetup also highlights opportunities for project grants and bounties, offering participants access to resources that can help turn their ideas into reality. Supported by Meta Pool and Kaia Network. The first event to take place on Saturday the 21st of September]

Bounty track
- Community

**Comment by zxstim** [comment]
Approved. Upload photos to X and submit receipts to claim bounty.

**Comment by zxstim** [comment]
https://x.com/gem_decrypto/status/1837509333720224200

for reference

**Comment by zxstim** [comment]
Closing this. Open a new one for next meetup.
