### ISSUE TITLE
Proposal: NFT-Based Virtual Pets

### ISSUE THREAD

**Issue by ExtraCaterpiller** [kaiachain/kaia-dapp-mono#129]
Description
- This project is a gamified NFT platform where users can own, take care of pets in a decentralized ecosystem
- Each NFT pet is unique, with dynamic stats that evolve through regular care, feeding and training
- Beyond gameplay, this project will also offer an educational layer where users can learn about real-world pet care and responsible ownership through fun, interactive experiences

Bounty track
- NFT, Other

**Comment by zxstim** [comment]
Sounds interesting. Apaproved. Don't forget Kaia has [Opensea.io](https://opensea.io/), so leverage the platform to help make your game more interesting (like incorporating some pet trading mechanism).

**Comment by ExtraCaterpiller** [comment]
Petiverse: NFT Pet Game:
https://petiverse-three.vercel.app/

Frontend repo: https://github.com/ExtraCaterpiller/Petiverse-frontend
Backend repo: https://github.com/ExtraCaterpiller/Petiverse-backend
Smart contract: https://github.com/ExtraCaterpiller/Petiverse-foundry

Deployed contract address
Kairos: 0xCafEA8FD4D039F5061DCEDCE0D8c4145c1123253

**Comment by zxstim** [comment]
hey hey will get back to you soon

**Comment by ExtraCaterpiller** [comment]
hello, @zxstim, did you review the project?

**Comment by zxstim** [comment]
A decent start. I think you can improve a lot more with random stats for battle. But just a suggestion. Feel free to make decision on how you can build up the gameplay.

`2000 KLAY` payout approved

**Comment by zxstim** [comment]
Another thing, you need to switch your Foundry command from using `--private-key` flag to `--account` for security. No payout until you change this.

**Comment by zxstim** [comment]
If you submit again, feel free to ping me every 2 days or so. I got a bunch of new submissions so I often forget and github is still bad on filtering. Prob need a new `submitted` tag

**Comment by ExtraCaterpiller** [comment]
Thanks for the feedback. I updated the foundry command. You can check now.

Regarding the battle, I am still thinking about it. Including randomness in some of the stat, I think will improve the engagement and experience of players because it will not feel repetitive. I need to think some more to decide

**Comment by ExtraCaterpiller** [comment]
Here's the smart contract repo link: https://github.com/ExtraCaterpiller/Petiverse-foundry

**Comment by ExtraCaterpiller** [comment]
Hello @zxstim, if it is alright would you please complete the payout?

**Comment by zxstim** [comment]
@ExtraCaterpiller payout request already submitted. i think monday will be disbursed.

meanwhile, can you open a PR and add yourself into the hall of fame here.
https://github.com/kaiachain/kaia-dapp-mono/blob/main/builder-program/hall-of-fame.md
