### ISSUE TITLE
Proposal: Meetup online

### ISSUE THREAD

**Issue by tungleanh0902** [kaiachain/kaia-dapp-mono#132]
Description
- Discuss gas optimization in evm smart contracts. The meetup will take place on Sunday the 29th of September.
- Link invite: https://lu.ma/07mqewbe

Bounty track
- Education

**Comment by zxstim** [comment]
Cool. Can you record the online meetup and post on your youtube channel or something?

**Comment by tungleanh0902** [comment]
Yeah sure

**Comment by tungleanh0902** [comment]
Hi, this is the meeting record: https://www.youtube.com/watch?v=cDZrNr5sDLo

**Comment by zxstim** [comment]
Approved for `100 KLAY` payout. Make sure you have the dorahacks BUIDL.

**Comment by zxstim** [comment]
Closing for payout
