### ISSUE TITLE
Proposal: Gammarix Uniswap V2 fork on Kaia

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#133]
Description
- Gammarix DeFi Protocol will fork Uniswap V2 onto Kaia and maintain a set of trading environment for other developers
- Will start out in testnet mode first then slowly go to mainnet (for safety)

Bounty track
- DeFi

**Comment by zxstim** [comment]
Cool. Approved.

**Comment by haxxsniper** [comment]
Github repos: 
https://github.com/gammarix/uni-v2-core
https://github.com/gammarix/uni-v2-periphery

Deployed at:
| Network | Factory Contract Address | V2Router02 Contract Address |
| ------- | ------------------------ | --------------------------- |
| Kaia Kairos | [0x82429c2D18d0B68D894DB26167DeACa904765BF2](https://kairos.kaiascan.io/address/0x82429c2d18d0b68d894db26167deaca904765bf2?tabId=internalTx&page=1) | [0xf96BbB746d2E7959Cf3eBC4C361D93768e3e802b](https://kairos.kaiascan.io/address/0xf96BbB746d2E7959Cf3eBC4C361D93768e3e802b?tabId=internalTx&page=1)       |


Dorahacks BUIDL: https://dorahacks.io/buidl/16614

**Comment by zxstim** [comment]
Approved for `2000 KLAY` payout. Great write up explainer and deployment process.

Closing for payout.
