### ISSUE TITLE
Proposal: Fork Permit2

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#134]
Description
- This proposal is to fork the Uniswap Permit2 to Kaia to expand the DeFi possibilities on Kaia. Permit2 is an innovative upgrade of the original Permit that allows signature based transfer of tokens without the need of a transaction created for approval.

The aim of this fork is to:
1. Increase User experience: Since Permit2 is designed specifically for tokens that does not implement the original permit functionality to use signature based transfers, it will enable increased user experience as it is most especially designed to enable batch transfers without sending a transaction.
2. Increase Adoption: By implementing Permit2 on Kaia, there can be a number of applications that improve user experience being developed on Kaia which could eventually increase overall liquidity.

Bounty track
- DeFi

**Comment by zxstim** [comment]
Much needed fork. Approved.

**Comment by PaulElisha** [comment]
These are the build links:

https://github.com/PaulElisha/Permit2
https://dorahacks.io/buidl/16651

**Comment by zxstim** [comment]
Approved for `2000 KLAY` payout.

**Comment by zxstim** [comment]
Closing for payout
