### ISSUE TITLE
Proposal: NFT Snapshot tool

### ISSUE THREAD

**Issue by chauanhtuan185** [kaiachain/kaia-dapp-mono#14]
Description
- Support projects in identifying the holders of an NFT collection

- Save them into a list, and airdrop tokens to these holders

- Interaction is facilitated through a Telegram bot.

Bounty track
- [add the name of the bounty track here]

**Comment by zxstim** [comment]
I think telegram bot might be a big UI pitfall here given the more complex interactions. But you can try and update me.

**Comment by chauanhtuan185** [comment]
@zxstim long time to take this into action 
I just create repo for this bounty 
https://github.com/chauanhtuan185/nft-cli-airdrop

**Comment by zxstim** [comment]
Approved for `1000 KLAY` payout.

**Comment by zxstim** [comment]
Closing for payout
