### ISSUE TITLE
Optimized Gas Fees Handling

### ISSUE THREAD

**Issue by Dreyomoba** [kaiachain/kaia-dapp-mono#142]
Gas Fee Estimates: Provide real-time gas fee estimates for transactions, including insights into how network conditions impact fees.
Fee Optimization Recommendations: Implement suggestions for users to adjust transaction timing based on network congestion to save on gas fees.

**Comment by zxstim** [comment]
What are your deliverables for this proposal?

**Comment by Dreyomoba** [comment]
I will create an algorithm that tracks and analyzes Klaytn network congestion to suggest the most optimal times for users to complete their transactions, minimizing gas fees.

Technical Approach:

I will build a backend system that collects and monitors Klaytn's historical gas fee data, identifying trends in network activity and pinpointing times of lower congestion. This data will be used to generate real-time recommendations, advising users on the best times to submit transactions when gas fees are reduced.

User Interaction:

I will implement a “Suggested Time” feature in the transaction interface. This will provide users with a recommendation, directly within the dApp, on when to proceed with their transactions based on current network conditions, ensuring they can minimize transaction costs

**Comment by zxstim** [comment]
I can see the technical merit of this proposal but Kaia gas fee is so low that it's not a very useful proposal.

I would mark this proposal `invalid` and close. Feel free to propose another idea.
