### ISSUE TITLE
Proposal: Onboarding Builders X Space

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#144]
Description
- It focuses on introducing the Kaia chain to builders.
- Open developer's workshop.
- Training sessions on how to build on Kaia using solidity and foundry.
- and How to build on Line.

Bounty track
- [add the name of the bounty track here]

**Comment by zxstim** [comment]
You should amend this issue for each session/workshop you want to run.

**Comment by PaulElisha** [comment]
> You should amend this issue for each session/workshop you want to run.

Okay.

**Comment by PaulElisha** [comment]
https://dorahacks.io/buidl/16795

https://x.com/paulelishaa/status/1840466012317294658

**Comment by zxstim** [comment]
Approved for `200 KLAY` bounty. Closing for payout.
