### ISSUE TITLE
Update: Revamp UI/UX for the wallet with refined flows - GMGN wallet

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#147]
Description
- Updated all the core functionalities for the wallet
- Added Pay + Request feature for requesting payment
- Added transaction memo to aid with identifying tx id
- Added faucet for Kaia Kairos to help onboarding flow
- Revised Send and Receive flow for better UX
- Added validation to various input
- Revised Sign and Signature features for better validation and UX

Reference issue
- #124 
- https://dorahacks.io/buidl/15990

Category
- Other

**Comment by zxstim** [comment]
Looking great. Approved

**Comment by haxxsniper** [comment]
Link: https://www.gmgn.app/

Source code: https://github.com/gmgn-app/gmgn

**Comment by zxstim** [comment]
Great improvements. The faucet is implementation is great.

Approved the max `2500 KLAY` payout.

**Comment by zxstim** [comment]
Closing for payout
