### ISSUE TITLE
Update: ShitFire Version 2.0 - Platform that allows users to shoot Shit NFTs to each other

### ISSUE THREAD

**Issue by SaitamaCoderVN** [kaiachain/kaia-dapp-mono#148]
Description
- I will clean up the code for this source and contract, research security methods to optimize the security of this contract.
- Designed to add a function to show the list of wallets that received the most shitNFT
- Complete ShitCoin P2P staking and trading functions on the website

Reference issue
- Related issue: https://github.com/kaiachain/kaia-dapp-mono/issues/100

Category
- NFT & DeFi. Categories are here: https://dub.sh/7zwejAg

**Comment by zxstim** [comment]
Approved to proceed

**Comment by SaitamaCoderVN** [comment]
This is ShitFire - Platform that allows users to shoot Shit NFTs to each:
https://shit-fire.vercel.app/

This is ShitFire Token address:

0xc51abA1430a00998ff522214Fa4AF8E61500CFce


This is ShitFire NFT address:

0x4e28C490245ba5611E2FeddfCBB8f9E31b1F037a


This is ShitFire Staking address:

0x223a8c6c00A61cC95d44162C35D26B29F226c485


This is contract repo:
https://github.com/SaitamaCoderVN/ShitFire-Contract-Foundary-Kaia-Blockchain

This is front-end repo:
https://github.com/SaitamaCoderVN/ShitFire

**Comment by zxstim** [comment]
Approved for `2000 KLAY` bounty payout

**Comment by zxstim** [comment]
closing for payout

**Comment by zxstim** [comment]
You should also fix your NFT metadata in the next submission
https://kairos.kaiascan.io/nft/0x9b9bb80035e4e0b9e0c372233785317cd3ef804e/20?tabId=nftTokenTransfer&page=1

try to get it to show up like
https://kairos.kaiascan.io/nft/0x5d98e2c833d8e9a70fee8b271fed59b4374c8ef6/10?tabId=nftTokenTransfer&page=1

**Comment by SaitamaCoderVN** [comment]
Yeah, I will improve it in the next update with the app having random functionality available on the Kaia blockchain


> You should also fix your NFT metadata in the next submission https://kairos.kaiascan.io/nft/0x9b9bb80035e4e0b9e0c372233785317cd3ef804e/20?tabId=nftTokenTransfer&page=1
> 
> try to get it to show up like https://kairos.kaiascan.io/nft/0x5d98e2c833d8e9a70fee8b271fed59b4374c8ef6/10?tabId=nftTokenTransfer&page=1
