### ISSUE TITLE
Proposal: Offline workshop at PTIT, Hanoi, Vietnam

### ISSUE THREAD

**Issue by tungleanh0902** [kaiachain/kaia-dapp-mono#149]
Description
- The workshop will take place at Post and Telecommunications Institute of Technology in Hanoi. The workshop is about introducing blockchain technology, how the technology is applied to our lives, about kaia blockchain, how kaia can help builders to build dapp on kaia, and the hackathon event that kaia is hosting with the students there. The workshop will take place on Wednesday the 9th of October.

Bounty track
- education

**Comment by zxstim** [comment]
This is great! Approved `700 KLAY` budget for you.

**Comment by tungleanh0902** [comment]
I'm sending you images from the workshop. 
![4](https://github.com/user-attachments/assets/68a76586-9649-4b05-b8e0-73955ad98886)
![2](https://github.com/user-attachments/assets/640d9356-e841-40ce-b2fc-7c7a25c72068)
![1](https://github.com/user-attachments/assets/eb493573-bf7b-47ae-afd1-f0cbcbd42fb4)
![3](https://github.com/user-attachments/assets/9c8a1834-809b-48e9-ab38-c188cf2a7edd)
![5](https://github.com/user-attachments/assets/f5ce7144-0cd9-47c7-a98f-e201544c70ba)
![6](https://github.com/user-attachments/assets/79622e37-bae6-44d2-b477-69f30e3dff21)
![7](https://github.com/user-attachments/assets/af355361-d3fd-4712-b4b0-0ff4e571f3a9)
Here is the social post: https://www.facebook.com/share/p/xHvBvubVpTqQ1cTF/

**Comment by zxstim** [comment]
Increase approval to `810 KLAY` for the workshop. Closing for payout.
