### ISSUE TITLE
Proposal: OKLink SDK to query block explorer in TS

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#15]
Description
- Implement an SDK for OKLink block explorer in TS

Bounty track
- [Contribute an Open Source Developer Tool](https://dorahacks.io/daobounty/444)

Building on top of: https://github.com/klaytn/klaytn-dapp-toolkit/issues/59

**Comment by zxstim** [comment]
Approved to proceed. Submit the implementation here after.

**Comment by zxstim** [comment]
Can you also add:
- [Transaction](https://www.oklink.com/docs/en/#blockchain-general-api-transaction)
- [Token](https://www.oklink.com/docs/en/#blockchain-general-api-token)

**Comment by haxxsniper** [comment]
I have updated the SDK to include methods for transaction and token API endpoints

**Comment by zxstim** [comment]
I will close this issue. If you want to build up more on top of this SDK, open a new issue and reference this issue.
