### ISSUE TITLE
Proposal: Open source contribution Meeting

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#151]
Description
- The meeting focuses on discussing what open source contribution is all about.
- It explains the ethos of open source contribution
- and how to start contributing to open source.
- A practical or walkthrough session showing developers or builders how to contribute to open source.

Bounty track
- Education
![mm](https://github.com/user-attachments/assets/37b9173e-09ae-4f65-a6b6-4f25498d4b49)

**Comment by zxstim** [comment]
![image](https://github.com/user-attachments/assets/22a64be7-4ae4-4e35-8568-be680b6f8f8b)

for reference

**Comment by zxstim** [comment]
Approved for `150 KLAY` payout

**Comment by zxstim** [comment]
Closing for payout
