### ISSUE TITLE
Proposal: JobJam

### ISSUE THREAD

**Issue by lyledavids** [kaiachain/kaia-dapp-mono#153]
Description
- JobJam: Revolutionising freelance work by providing a decentralised, transparent, and secure platform for connecting employers and freelancers through smart contracts.

Similar projects - Bountybot on Warpcast and Dework

Bounty track
- Other

Deployment - https://jobjamkaia.netlify.app/

Github repo - https://github.com/lyledavids/jobjam

Contract - https://github.com/lyledavids/jobjam/tree/main/contracts

Dorahacks - https://dorahacks.io/buidl/16900

What next? 
- 1-on-1 chat using xmtp. Chat between client and freelancer is common before work is done and before payment is done. Makes thing move quicker between client and freelancer
- Integration with Subquery or alternative. Job feed data is currently being called directly from blockchain, not good for UX especially if many more jobs are added
- error prevention functions
- UI fixes

Some Screenshots 
- Employer
![Screenshot 2024-10-06 at 00 21 12](https://github.com/user-attachments/assets/4a5cd875-e734-4265-8b41-a8b10ae91a9a)
![Screenshot 2024-10-06 at 00 20 17](https://github.com/user-attachments/assets/20e4142c-3738-476b-8876-b58c37aa638d)
![Screenshot 2024-10-06 at 00 20 23](https://github.com/user-attachments/assets/761a9c52-d39b-45b5-9242-0175ba2b8845)
![Screenshot 2024-10-06 at 00 20 52](https://github.com/user-attachments/assets/d54b05ed-99af-4b52-9ea4-ca8d9a6df210)

- Freelancer
![Screenshot (325)](https://github.com/user-attachments/assets/8e818e74-8e25-43c1-85cd-bac7ab1d9a2d)

-General(Both freelancer and employee)
![Screenshot (326)](https://github.com/user-attachments/assets/f52aee5f-62a0-4faf-9af0-3d3b4d7136eb)
![Screenshot 2024-10-06 at 01 11 32](https://github.com/user-attachments/assets/b4723bf9-8de4-42c7-8f6c-41a0bcb25035)
![Screenshot 2024-10-06 at 00 20 04](https://github.com/user-attachments/assets/a26ff462-b546-45b2-948b-b896ec8ce1ff)

**Comment by zxstim** [comment]
Approved. Give me a day or so to consider a bounty amount for this.

I think this is an ok start. Freelance settlement process has issues though. There are frauds on both sides of the aisle here (both from employer and employee)

My thinking is you should add an arbitration process (like 24 hour for initial dispute, then multi-stage escalation). Initially, the platform can be the arbitrator (this is similar to existing web2 platform). Long term, you want to add in token incentives for a group of public arbitrators (or practically anyone). Many proposals won't need arbitration but the ones that do, would go through voting by the arbitrators to settle.

You can read up on optimistic oracle like UMA protocol https://uma.xyz/#how-it-works

**Comment by lyledavids** [comment]
Okay, thanks

I normally use Upwork to do freelance work. I noticed that disputes do happen between other freelancers and their clients. This is usually handled by the Upwork team. I was considering integrating Kleros to handles disputes, will take at UMA as well.

**Comment by zxstim** [comment]
Kleros works too.

Anyway, `2500 KLAY` bounty approved. I will include this under a new Consumer app category

**Comment by zxstim** [comment]
Closing for payout

**Comment by lyledavids** [comment]
Kleros and UMA don't have support for Kaia
Tried to build a something similar in Remix please check it out.
No frontend, just contract. Will have frontend in future update proposal
https://gist.github.com/lyledavids/458e21a800d328074e7998bfdbf59f10

**Comment by lyledavids** [comment]
Any feedback on the dispute contract above would be appreciated.
Would love to add it in

**Comment by zxstim** [comment]
You should open a new issue with the smart contract as an Update. Maybe just focus on the arbitration contract entirely for the next submission.

Give me a few days to review the smart contract. I am reviewing other submissions right now.
