### ISSUE TITLE
Proposal: Understanding EIP 712: A beginner's guide

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#158]
Description
- This proposal is for a comprehensive article that explains EIP 712. 
- The article explains covers a background on EIP 191 signature standard as a basis for understanding EIP 712.
- It explains the format of EIP 191 and EIP 712 signature standard that ensures signing typed structuring data.
- It covered the concept of version specific data, domain separator and message typeHash.
- A signature verifier contract was constructed to practically show how EIP 712 format in code.
- We demonstrated the use of EIP 712 using OpenZeppelin.
 
  Why this proposal should be approved?

- It will set a prerequisite guide to explain the Permit2.
- It will give a good understanding on how to implement signatures based permission.
- It contains an airdrop dirstribution contract to explain how to leverage EIP-712 for type structured data and meta transactions.

Bounty track
- Education

**Comment by zxstim** [comment]
Approved to proceed

**Comment by PaulElisha** [comment]
Done.

https://github.com/PaulElisha/kaiachain-dapp-mono/tree/EIP712-Guide
https://dorahacks.io/buidl/17049

**Comment by zxstim** [comment]
Approved for `650 KLAY` bounty payout
