### ISSUE TITLE
Update: Airdrop Distribution Contract implementing signature based permission and gasless transaction using the fee payer logic.

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#159]
Description
- A signature update has been made to the airdrop distribution contract.
- It demonstrates the integration of EIP 712 signature standards.
- It showcases how to implement the signature format of EIP 712 using the OpenZeppelin Library.
- It ensures signatures are used to determine an approved claimer.
- It uses signatures to implement a fee payer logic in airdrop claiming.

Reference issue
- The update was made to #106

Category
- DeFi

**Comment by zxstim** [comment]
Here is my address on Kaia Kairos: 0x6a672dD588577E3d4b57c45CDDA243129b80847d

Set up an airdrop that only this address can claim on Kairos using your Merkle airdrop setup. I want docs, step by step setup, what do I have to do to claim.

**Comment by zxstim** [comment]
Approved for `1500 KLAY` payout. Need better docs for next submission tho. Will comment my expectation below.
