### ISSUE TITLE
Update: Improved payment flow and stablecoin integration for GM GN Wallet

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#160]
Description
- Improved payment flow for users
- Improved fee delegation flow
- Kaia mainnet activation
- Stablecoin integration
- Getting started section for users

Reference issue
- #147

Category
- Other. Categories are here: https://dub.sh/7zwejAg

**Comment by zxstim** [comment]
Approved. I like stablecoin adoption for payment btw.

**Comment by haxxsniper** [comment]
Send me your address so I can mint you some stablecoins

**Comment by zxstim** [comment]
My address is here: 0x4Fa9a6c995b8Fa9463b472127e8e90D711fEb392

**Comment by haxxsniper** [comment]
Minted. Also updated.

Link: https://www.gmgn.app/

Source code: https://github.com/gmgn-app/gmgn

Dorahacks BUIDL: https://dorahacks.io/buidl/15990

**Comment by zxstim** [comment]
Approved for `2000 KLAY` payout. This looks great.

**Comment by zxstim** [comment]
Closing for payout
