### ISSUE TITLE
Proposal: Open-source bridge CEX

### ISSUE THREAD

**Issue by chauanhtuan185** [kaiachain/kaia-dapp-mono#167]
Description
Asset transfers across chains have become easier than before, but there are still significant risks regarding the reliability of smart contracts. Additionally, transaction costs can be a deterrent.

I propose developing an open-source toolkit that allows users to automatically create their own cross-chain bridge using CEX platforms (Binance, OKX).

- Launch the program and add a whitelist of exchange wallet addresses to the default configuration.
- Listen for deposit events and automatically withdraw funds to predefined wallets.
- Integrate cross-chain and multi-exchange functionality.

Bounty track
- Developer tool

**Comment by zxstim** [comment]
Approved. Interesting to proceed. I think a telegram bot as interface works too since this system should be self deploy

**Comment by chauanhtuan185** [comment]
@zxstim hi , i just complete mvp for this 
https://github.com/chauanhtuan185/opensource-bridge-cex/tree/main

**Comment by chauanhtuan185** [comment]
This is a video demo : https://youtube.com/shorts/UjZ7sbdW4oc?feature=share

**Comment by chauanhtuan185** [comment]
@zxstim hi ser , pls review it . Tks so much

**Comment by zxstim** [comment]
great work. Approved for `1700 KAIA` bounty

**Comment by zxstim** [comment]
closing

**Comment by zxstim** [comment]
can you copy the dorahacks BUIDL link here?

**Comment by chauanhtuan185** [comment]
Link to my build on dorahack : https://dorahacks.io/buidl/17097

**Comment by chauanhtuan185** [comment]
@zxstim
