### ISSUE TITLE
Beyond the Ledger: Exploring the Magic of Web3 Oracles in Kaia Blockchain

### ISSUE THREAD

**Issue by detty-dev** [kaiachain/kaia-dapp-mono#168]
Description
- [describe what the submission is]
In this article we will explore how oracles function, their types (pull-based and push-based), and how they integrate with the Kaia blockchain. We will examine practical examples of fetching real-time data and generating random numbers, showcasing the potential of these innovative tools in shaping the future of decentralized applications.

Bounty track
- [add the name of the bounty track here]
Content writing

**Comment by zxstim** [comment]
Approved the article proposal but your submitted article is too simple for a technical writing.

I can assign higher bounty for article given the quality. Need you to actually deep dive into the different oracle design, especially with the leading protocols (Chainlink and Pyth).

**Comment by detty-dev** [comment]
Can this pass while I do my research on the  architecture designs of the protocol’s you mentioned

**Comment by zxstim** [comment]
unfortunately no. You would need to improve the article and edit your PR. The higher quality writing, the more technical details, the higher the payout.

**Comment by detty-dev** [comment]
Alright, I am at it.

**Comment by zxstim** [comment]
Pasting link for reference: https://github.com/detty-dev/kaia-dapp-mono/blob/web3oracle/learn/Beyond%20the%20Ledger%20Exploring%20THE%20MAGIC%20OF%20WEB3%20ORACLES%20IN%20Kaia%20Blockchain.md

**Comment by zxstim** [comment]
Good work. Approved for `1000 KLAY` payout.

**Comment by zxstim** [comment]
Besides the PR, can you also create a repo in your github to host this guide, add some more sample codes inside as well, turn your guide into a full kit for more rewards.

**Comment by zxstim** [comment]
Closing for payout
