### ISSUE TITLE
Proposal: Kaia Burger Rush Blockchain Game

### ISSUE THREAD

**Issue by lunanga486** [kaiachain/kaia-dapp-mono#171]
**Description**
- **Engaging Gameplay and Attractive Graphics:** Kaia Burger Rush Blockchain Game offers highly engaging gameplay with beautiful graphics.
- **NFTs for Power-ups:** Players can purchase in-game NFTs using KLAY to gain power-ups and enhance their gaming experience.
- **In-game Currency Purchases:** Players are also able to buy in-game currency using KLAY.
- **Ecosystem Integration:** The game enhances Kaia's gaming ecosystem by integrating blockchain features.
- **MetaMask Integration:** It connects with Kaia through MetaMask for seamless user interaction.

**Bounty track**
- Other & NFT.

**Note:**
Because I didn't read carefully, I developed my own product and connected with Kaia. You can experience the entire product through the links below.
My mistake, so if it's not approved, consider it a small contribution from me to the Kaia community.
Thanks.

**Game Link:**
https://lunanga486.itch.io/kaia-burger-rush-game

**Github Link:**
https://github.com/lunanga486/Kaia-Burger-Rush-Game

**Video link:**
https://www.youtube.com/watch?v=NuNsgdMqAkU

**Comment by zxstim** [comment]
Hmmm... I think ok. For this kind of game, ideally i think you should just focus on gameplay, use crypto rails for payment and rewards (NFTs, tokens)

I think this is a decent start.

Approved for `1500 KLAY` bounty payout.

**Comment by lunanga486** [comment]
@zxstim 
Dear zxstim ,

So can we close this issue and proceed with payment?
Or do I need to do anything else?

Thanks and best regards.
