### ISSUE TITLE
Proposal: Proposal to create a tool to build Json data in Solidity

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#172]
Description
- This proposal is to create a developer tool for building json structures in solidity.
- It leverages foundry std-json library.

Why Proposal?
- Useful when gathering data to store in a Merkle Tree for Airdrop.
- Useful in a complex NFT-based project like gaming projects that claims NFT in-game, dynamic NFTs, to structure data efficiently and for project scalability.
- Useful in structuring and transferring state data in Json form that can be decoded and managed elsewhere to sync state.
- Useful to build data that needs to be read on-chain efficiently.

Bounty track
- Developer tool

**Comment by PaulElisha** [comment]
Done.

**Comment by zxstim** [comment]
Can you elaborate your README a bit more (give some additional context) to highlight the following:
- what is this?
- **_why use this?_** -> you are lacking in this part
- how to do use this?

**Comment by PaulElisha** [comment]
I have updated it in that order, kindly check back.

https://github.com/PaulElisha/CreateJsonStructure

**Comment by zxstim** [comment]
Approved for `1500 KLAY` bounty payout. I think if you can tailor made this kit for different use case, that would be great.

**Comment by zxstim** [comment]
Closing for payout

**Comment by PaulElisha** [comment]
> Approved for `1500 KLAY` bounty payout. I think if you can tailor made this kit for different use case, that would be great.

okay. will do that.
