### ISSUE TITLE
Proposal: Offline Kaia Community Workshop at Obafemi Awolowo University, Ile-Ife, Osun State, Nigeria.

### ISSUE THREAD

**Issue by samlovework** [kaiachain/kaia-dapp-mono#173]
Description
- The Community Workshop will be a physical event and take place at the Student Union Building Hall, at Obafemi Awolowo University, Ile-Ife, Osun State, Nigeria. 

The workshop is about introducing Blockchain Technology, introducing Kaia blockchain, kaia mission and uniqueness in the Web3 space. 

In addition, how Kaia can help builders to build Dapp on Kaia, how Non-tech Web3 enthusiasts, writers can contribute to kaia blockchain and a community can be started after the event.

I intend to collaborate with @Oxpampam and @PaulElisha as speakers for the workshop.

The Workshop will take place on Saturday, 16th of November, 2024.

Bounty track
- Education and Community.

**Comment by zxstim** [comment]
Approved. Regarding budget:
- Typically I grant 5-10 KLAY to attendees for trying out Kaia (for devs, this will be their mainnet gas for deployment)
- We will cover coffee and light pastry cost
- A bit extra for you to cover your own expenses

Upload photos of the workshop on X (we will RT/QT) then submit the link here to claim your compensation.

**Comment by samlovework** [comment]
Okay.

It's a large size event, what budget do you suggest I work with?

**Comment by zxstim** [comment]
depends on how many people, make a guess, but the breakdown is above. you can roughly add them all up for the cost

**Comment by samlovework** [comment]
Hi, below is a proposal breakdown for 100 people for the event.
![Screenshot_2024-10-26-22-12-38-352_com google android apps docs editors docs](https://github.com/user-attachments/assets/726d679d-3b10-4592-824e-b099c786b225)

**Comment by samlovework** [comment]
Hi, below is the link of our Offline Kaia Community Workshop at Obafemi Awolowo University, Ile-Ife, Osun State, Nigeria.

[https://x.com/samlovework/status/1858185820919730528?t=ljQ5qmtdn5ne9IkIOzXyHQ&s=19]

![IMG-20241118-WA0026](https://github.com/user-attachments/assets/dbc31d0f-ea00-424d-be4c-e042d97c3a5c)
![IMG_20241116_160037_653](https://github.com/user-attachments/assets/dc77642a-2d0c-4f64-b52f-78907dc84798)
![IMG_20241116_164728_7](https://github.com/user-attachments/assets/cdb4feb3-4e9c-4e5c-8b4d-a9e1e2758767)

**Comment by zxstim** [comment]
Pre-approved for `860 KAIA`. Final approve for `1270 KAIA`.

**Comment by zxstim** [comment]
Closing
