### ISSUE TITLE
Proposal: Workshop online

### ISSUE THREAD

**Issue by tungleanh0902** [kaiachain/kaia-dapp-mono#174]
Description
- An online workshop to introduce basic solidity with students in PTIT. In this workshop, I will present basic knowledge of solidity, how to write a smart contract, how to unit test it and interact with deployed smart contracts using script, and some techniques often used in practice when developing smart contracts run on EVM. I also support students who have ideas to submit to Kaia Fall Odyssey. This workshop will be held at 2 p.m. on Sunday 20th October.
- Link: https://lu.ma/p00xfr4,

Bounty track
- Education

**Comment by zxstim** [comment]
Approved. Make sure you record the session or livestream it to be posted on social media.

**Comment by tungleanh0902** [comment]
Hi, this is the meeting record posted on youtube: https://youtu.be/Dyv_FqI09fA

**Comment by zxstim** [comment]
Can you make it public instead of unlisted? we can share it so you can build your followings?

**Comment by zxstim** [comment]
Approved for `200 KLAY` bounty payout

**Comment by zxstim** [comment]
And can you add yourself to the hall of fame here 
https://github.com/kaiachain/kaia-dapp-mono/blob/main/builder-program/hall-of-fame.md

**Comment by tungleanh0902** [comment]
Yeah I just make my videos public and I will add myself to the hall of fame.
