### ISSUE TITLE
Proposal: Tool for replace exposed private key

### ISSUE THREAD

**Issue by vadrthanh** [kaiachain/kaia-dapp-mono#175]
Description
- Currently, Kaia Wallet allows users to change their private key, but it requires them to write code and perform many complicated steps. This tool allows users to replace their private key when it's compromised with just a few simple actions.
- This is a UI tool that allows users to easily replace their private key when it is exposed.
- Frontend only, no backend or smart contract.

Bounty track
- Other (Private key replacement Tool)

**Comment by zxstim** [comment]
Approved to proceed. Revert back with github links and web link.

**Comment by zxstim** [comment]
hmm... given the sensitive nature of this. Can you make it into a plain html, css, js combo, something i just download from github to my computer, open the `index.html` file to use

just minimal css for ease of use

**Comment by zxstim** [comment]
but I will approve this submission for `1000 KLAY`. Convert to html, css, js combo to claim the remaining `500 KLAY`.

**Comment by zxstim** [comment]
https://dorahacks.io/buidl/17865

you need to follow the format here
https://dorahacks.io/hackathon/kaia-fall-odyssey/detail#submission-guidelines

**Comment by vadrthanh** [comment]
Thank you very much, i will do it right now

**Comment by vadrthanh** [comment]
Dear @zxstim,

I hope you're doing well. I understand that "Convert to HTML, CSS, JS combo to claim the remaining" means I will not be using React for deployment. Could you kindly confirm this?

Also, I haven’t received the Kaia tokens yet. Would you mind checking the payment status for me? Here’s my address: 0x12566464084226894bc76c9cd92b081ef4d3112d.

My sincere apologies for the delay in reaching out.

Thank you very much for your assistance.

**Comment by zxstim** [comment]
Ah i really did forget to payout here.

Adjusted payout to current KAIA market rate

`550 KAIA`
