### ISSUE TITLE
Proposal: Create a new clothing shopping experience with a 3D clothing store. Where players buy NFT clothes. Then use this NFT to get real clothes.

### ISSUE THREAD

**Issue by langsky302** [kaiachain/kaia-dapp-mono#177]
Description:
- The submission is a 3D Clothing Store Experience, a virtual shopping platform where players explore a beautifully designed 3D store to purchase NFT clothes.
- The NFTs represent exclusive digital versions of real clothing items.
- Players can browse different sections of the store, interact with the garments.
- Once a player buys an NFT, they can redeem it for the corresponding real clothing item, bridging the virtual and physical worlds.
- The experience combines fashion, gaming, and blockchain technology, providing a unique and engaging way to shop for and collect exclusive fashion pieces.

Bounty track
- Other and NFT.

![Image3](https://github.com/user-attachments/assets/ab5cd93f-1fe9-45e6-90e1-efb25760adf2)
![Image1](https://github.com/user-attachments/assets/4def7e19-c3fb-4e38-bc1e-4c84081831e5)
![Image2](https://github.com/user-attachments/assets/5f2d00f8-5572-4c90-adf7-bf3623ed58d9)
![Screenshot 2024-10-12 161849](https://github.com/user-attachments/assets/8c31c0c4-b9a4-4b37-995d-ea30fdea7035)

**Comment by zxstim** [comment]
Cool. I will edit the track for you later. This should fall in our new Consumer track.

**Comment by langsky302** [comment]
Hey @zxstim ! 🎉

Thrilled to share that the Kaia Clothing Store project is complete! After two intense weeks of nonstop work with 3D modeling and coding, we’ve crafted a unique shopping experience that blends NFTs and immersive 3D.

Here’s everything to explore:

[GitHub](https://github.com/langsky302/Kaia-Clothing-Store-Project) 📂
[Live Demo](https://langsky302.github.io/Kaia-Clothing-Store-for-Shopping/) 🛒
[Demo Video](https://www.youtube.com/watch?v=LJDnEyTl2v8) 🎥

Can’t wait for you to try it out and let me know what you think! 🔗✨

**Comment by zxstim** [comment]
approved `1250 KAIA` bounty

**Comment by zxstim** [comment]
closing
