### ISSUE TITLE
Proposal: Foundry template to deploy smart contracts on Kaia

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#18]
Description
- A Foundry and Hardhat boilerplate to deploy smart contracts on Kaia.
- Boilerplate will try not to conflict much with the changes in core frameworks. Most of it will be peripheral scripts to aid development.
- Include deployment settings, documentation and various dev-ops utilities

Bounty track
- [Contribute an Open Source Developer Tool](https://dorahacks.io/daobounty/444)

**Comment by haxxsniper** [comment]
Can I not do Hardhat and go all in with Foundry template? I will include some really good stuffs with existing ecosystem projects?

**Comment by haxxsniper** [comment]
Please find the template here:
https://github.com/haxxsniper/kaia-foundry-template

I included token implementation, automated developer config, orakl integration and foundry toml file.

**Comment by zxstim** [comment]
looks ok. Need more docs and test though but I will approve this one. Come back with more docs and [Pyth](https://pyth.network/) integration for me.

Maybe include more stuffs. They don't have to be tied together. You can separate different workflows with `makefile`

Approved for 500 KLAY payout.

**Comment by zxstim** [comment]
Closing this Issue. Open new issue when you make additional updates.
