### ISSUE TITLE
Proposal: Sblinks - new experience for user in Kaia and EVM

### ISSUE THREAD

**Issue by chauanhtuan185** [kaiachain/kaia-dapp-mono#186]
Description
- Create a template for developer can create Dapp inside X post using X card component

Bounty track
- Developer Tool

**Comment by chauanhtuan185** [comment]
I have create repo about this template so any one use 
https://github.com/chauanhtuan185/Sblinks

**Comment by zxstim** [comment]
it's not accessible

**Comment by chauanhtuan185** [comment]
I just open repo to public

**Comment by zxstim** [comment]
Approved for `2000 KLAY` bounty payout

**Comment by zxstim** [comment]
Closing for payout
