### ISSUE TITLE
Proposal: Contribute the decentralized exchange (DEX) implementation/forks on Kaia

### ISSUE THREAD

**Issue by SaitamaCoderVN** [kaiachain/kaia-dapp-mono#19]
Description
- I will fork Dragon Swap (DEX) on Klaytn and comment in detail its source code 
Bounty track
- [add the name of the bounty track here]

**Comment by zxstim** [comment]
a much needed task for our ecosystem 👍
- Repo: https://github.com/dragon-swap-klaytn
- Feel free to ping back here if you have trouble

**Comment by FucktheKingcode** [comment]
> một nhiệm vụ rất cần thiết cho hệ sinh thái của chúng ta 👍
> 
> * Kho lưu trữ: https://github.com/dragon-swap-klaytn
> * Vui lòng ping lại đây nếu bạn gặp khó khăn

Yeah, I will send link my repo at here soon 🤣

**Comment by FucktheKingcode** [comment]
My repo: https://github.com/FucktheKingcode/dragon-frontend.git
You can swap Kaia to Meme coin (that is a token on Kaia testnet) on my repo
![image](https://github.com/user-attachments/assets/46dcb160-19a2-40af-8e29-2f90c12fc1f0)
![image](https://github.com/user-attachments/assets/008e48f0-ea08-4635-9473-9e88f74b1623)
![image](https://github.com/user-attachments/assets/4a5c6195-b6ab-4cda-9d00-f0863a62be54)

**Comment by zxstim** [comment]
Looks good. Approved for `1500 KLAY` payout for completing this task. Please help cleaning up the repo.

**Comment by zxstim** [comment]
After reviewing the codebase, I will reduce the payout to `500 KLAY` because most of the work has been done by dgswap team. Apology for the previous comment.

**Comment by zxstim** [comment]
Closing this issue. Open new issue if you want to make an update.
