### ISSUE TITLE
Update: GM GN Wallet integration with Wallet Connect to support all DApps

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#196]
Description
- Integrate Wallet Connect into GM GN Wallet to support all DApps on Kaia
- Overall cleanup to improve UX

Reference issue
- #160

Category
- Other

**Comment by zxstim** [comment]
Approved. Revert back with implementation

**Comment by haxxsniper** [comment]
Check the implementation here:
https://dev.gmgn.app/connect?network=kaia-kairos&address=0x3e747fE6Ccd221B9601324d8d76fca9CE0232108

you can interact with: https://www.blockcmd.com/drop/native

comments and docs included: https://github.com/gmgn-app/gmgn/blob/main/app/connect/page.tsx

**Comment by zxstim** [comment]
Approved for `2000 KLAY` bounty payout
