### ISSUE TITLE
Proposal: LeoFi Coffee Meetup

### ISSUE THREAD

**Issue by phamdat721101** [kaiachain/kaia-dapp-mono#197]
Description

About the Meetup
Join us for an immersive blockchain experience where DeFi innovation meets community collaboration. Backed by industry leaders LeoFi and Kaia Network, this meetup series brings together visionaries, developers, and blockchain enthusiasts to explore the cutting edge of decentralized finance.

Format

- Welcome & Networking
- Featured Presentation
- Technical Workshop/Demo
- Project Spotlights
- Open Discussion & Collaboration
- Casual Networking

Join us in creating the future of finance in a relaxed, collaborative environment. Whether you're a seasoned developer or just getting started in DeFi, there's a place for you in our community.

Time: 09:30AM - 12:00PM
Location: Vinhome grandpark

Bounty track

Community

**Comment by zxstim** [comment]
Approved.

Regarding budget:  
- Typically I grant 5-10 KLAY to attendees for trying out Kaia (for devs, this will be their mainnet gas for deployment)
- We will cover coffee up to $70-ish (give and take, not strict)
- A bit extra for you to cover your own expenses

**Comment by zxstim** [comment]
and make a luma to keep track of your meetup attendees and signup. Don't change the link, just edit the luma page after each meetup

**Comment by phamdat721101** [comment]
Luma link: https://lu.ma/90gu964d
Location: Blue space coffee - Vinhome grandpark(NX-LP TMDV1, 23 Đ. Nguyễn Xiển, Long Bình, Quận 9, Hồ Chí Minh, Việt Nam)

**Comment by zxstim** [comment]
👍 will help cover your coffee cost and small incentives for you. Approved

**Comment by zxstim** [comment]
Make sure you take photos and post social media (preferably X)

**Comment by phamdat721101** [comment]
> Make sure you take photos and post social media (preferably X)

Update Bitcoin Layer 2 Meetup 
https://twitter.com/LeoFi_Hub/status/1862891390226792510
cc @zxstim

**Comment by zxstim** [comment]
Approved `250 KAIA + 30 KAIA rewards = 280 KAIA`

**Comment by zxstim** [comment]
closing

**Comment by phamdat721101** [comment]
> Approved `250 KAIA + 30 KAIA rewards = 280 KAIA`

Build: https://dorahacks.io/buidl/20629
