### ISSUE TITLE
Proposal: Update to smart contract inspect tool

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#2]
Description
- An open source read/write to smart contract developer tool so that developers can interact with the smart contract on mainnet, testnet or local node
- Massive UI/UX overhaul to make usage easier with more funcitonalities

Migrated from:
- https://github.com/klaytn/klaytn-dapp-toolkit/issues/39

**Comment by haxxsniper** [comment]
You can find the newly deployed app here: https://inspect.blockcmd.com

Repo: https://github.com/blockcmd/inspect

**Comment by zxstim** [comment]
Great improvement over the previous version. Better UI/UX and better flow. Add Kaia as well please.

Approved for `2000 KLAY` bounty.
