### ISSUE TITLE
Proposal: A frontend React Application - K-Edu

### ISSUE THREAD

**Issue by MichaelOmoniyi** [kaiachain/kaia-dapp-mono#20]
Description
- The application would display several free and paid learning resources that users can access to gain more understanding of the Klaytn ecosystem and applications on the Klaytn ecosystem. The application would have access to the user's wallet and would contain a dashboard that displays the amount of Klay the user has, which the user can use to purchase paid learning resources on the application.
- As regards the learning resources, I mean materials (audio, video, written, or a combination of all) explaining to new or existing users how they could use applications that are on the Klaytn ecosystem. These materials would be provided by either a technical writer, developers, or any other person who has access to upload materials.

Bounty track
- Contribute an approved frontend app

**Comment by MichaelOmoniyi** [comment]
I've implemented the Learning platform called K-edu, which provides free, paid, and advanced resources to users. Users can connect their Klaytn wallet for payment. The courses are not standard yet, just test samples.

GitHub Repository: https://github.com/MichaelOmoniyi/klaytn-dapp-toolkit/tree/main/frontend/k-edu
Live link: https://k-edu-learn.netlify.app/

**Comment by zxstim** [comment]
This looks great!

Approved for payout for the track.

I would also recommend checking out our [bootcamp contents](https://github.com/kaiachain/kaia-dapp-mono/tree/main/bootcamp/en) and add that into your platform. Then I would qualify you for the 500 KLAY bounty track [Contribute an Open Source Developer Tool](https://dorahacks.io/daobounty/444).

**Comment by zxstim** [comment]
Also another recommendation, I see that you are using Create React App. Create React App has no longer been recommended for most production use (even from the React team). I would highly recommend you to explore [Nextjs framework](https://nextjs.org/). Learning education platform would benefit greatly with Server-side Rendering feature provided by the framework.

Nextjs is a React based framework so you can still use the same react code but with some tweaks.

**Comment by MichaelOmoniyi** [comment]
> Also another recommendation, I see that you are using Create React App. Create React App has no longer been recommended for most production use (even from the React team). I would highly recommend you to explore [Nextjs framework](https://nextjs.org/). Learning education platform would benefit greatly with Server-side Rendering feature provided by the framework.
> 
> Nextjs is a React based framework so you can still use the same react code but with some tweaks.

Noted, I'll looking the implementation of Nextjs in the Learning education platform.

**Comment by zxstim** [comment]
can you open a PR and edit this file with the information of your submission?
https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md

you can follow the previous edits
[submission description] - @[your-github-username] | Repos: ...

**Comment by MichaelOmoniyi** [comment]
> can you open a PR and edit this file with the information of your submission? https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md
> 
> you can follow the previous edits [submission description] - @[your-github-username] | Repos: ...

Okay, I'll do that

**Comment by MichaelOmoniyi** [comment]
> This looks great!
> 
> Approved for payout for the track.
> 
> I would also recommend checking out our [bootcamp contents](https://github.com/kaiachain/kaia-dapp-mono/tree/main/bootcamp/en) and add that into your platform. Then I would qualify you for the 500 KLAY bounty track [Contribute an Open Source Developer Tool](https://dorahacks.io/daobounty/444).

I already Implemented the BootCamp section. Here is the link to the live site: https://k-edulearningplatform-htogcriib.vercel.app/
I am still working on making it a next-js app. I should be done with that soon.

**Comment by MichaelOmoniyi** [comment]
> This looks great!
> 
> Approved for payout for the track.
> 
> I would also recommend checking out our [bootcamp contents](https://github.com/kaiachain/kaia-dapp-mono/tree/main/bootcamp/en) and add that into your platform. Then I would qualify you for the 500 KLAY bounty track [Contribute an Open Source Developer Tool](https://dorahacks.io/daobounty/444).

Good day sir, I received a mail that the bounty has been approved but it has not reflected in my trustwallet. For the 500 KLAY bounty do you suggest I create a new account and link my metamask wallet instead rather than using my current bounty account which has trustwallet linked.

**Comment by zxstim** [comment]
Try checking your address on block explorer. Sometimes, trust is not refreshing the balance due to RPC issues. 

you can hunt with the same account and address. But dorahacks platform works better with metamask.

**Comment by MichaelOmoniyi** [comment]
> Try checking your address on block explorer. Sometimes, trust is not refreshing the balance due to RPC issues.
> 
> you can hunt with the same account and address. But dorahacks platform works better with metamask.

Okay sir 
Thank you

**Comment by zxstim** [comment]
Hey @MichaelOmoniyi, can you make your vercel deployment to be public rather than requiring to log in to vercel?

**Comment by MichaelOmoniyi** [comment]
> Hey @MichaelOmoniyi, can you make your vercel deployment to be public rather than requiring to log in to vercel?

Good day sir, I have made the correction. This is the new link:
[k-edu.vercel.app](https://k-edu.vercel.app/)

**Comment by zxstim** [comment]
Content looks great. I will approve 500 KLAY for you. I would like you to make some big UI update coming up.

Make sure to edit your submission here (https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md) if it changed.

**Comment by zxstim** [comment]
And update the bounty submission here too
https://dorahacks.io/daobounty/444

**Comment by MichaelOmoniyi** [comment]
> Content looks great. I will approve 500 KLAY for you. I would like you to make some big UI update coming up.
> 
> Make sure to edit your submission here (https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md) if it changed.

Thank you sir

**Comment by MichaelOmoniyi** [comment]
> Content looks great. I will approve 500 KLAY for you. I would like you to make some big UI update coming up.
> 
> Make sure to edit your submission here (https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md) if it changed.

Good day sir, please I'm yet to get the approval

**Comment by zxstim** [comment]
I submitted you for bounty payout already. Should be soon.

**Comment by MichaelOmoniyi** [comment]
> I submitted you for bounty payout already. Should be soon.

Okay sir 
Thank you

**Comment by MichaelOmoniyi** [comment]
> I submitted you for bounty payout already. Should be soon.

I have gotten the payout already. Thank you

**Comment by zxstim** [comment]
Hey @MichaelOmoniyi, we just opened our showcase page on Dorahacks using their hackathon format. Feel free to submit your project on there as a BUIDL for visibility.

Also, keep building up on the education platform to earn more bounty.

**Comment by MichaelOmoniyi** [comment]
> Hey @MichaelOmoniyi, we just opened our showcase page on Dorahacks using their hackathon format. Feel free to submit your project on there as a BUIDL for visibility.
> 
> https://dorahacks.io/hackathon/kaia-onchain-summer/buidl
> 
> Also, keep building up on the education platform to earn more bounty.

Thanks, I'll do that 
What other features do you suggest can be implemented?

**Comment by zxstim** [comment]
Couple suggestions for you:
- You can upgrade the UI and re-organize the contents to be easier to navigate
- You can add more original contents (your own), make use of our library of contents on [here](https://klaytn.foundation/blog/?search=&blog_category=tutorials&sort=)

Based on your effort, I will assign an equivalent amount of KLAY for you.

**Comment by zxstim** [comment]
Anyway, closing this issue. Feel free to open a new issue for your updates.
