### ISSUE TITLE
Proposal: Building cross-chain applications leveraging layer zero

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#200]
Description
- This proposal is to build an application that leverages layer zero for cross-chain messaging.
- It demonstrates how to connect the same smart contract application on different chains and facilitate communication.
- It also shows how to create a simple cross-chain token using the Layerzero oft standard.

Why proposal?

This will enable developer quickly learn to integrate layer zero into their application for seamless cross-chain communication.
It will help developers connect mock lzEndpoints to unit test their applications.
It will enable projects to build applications on Kaia that maintain unified liquidity

Bounty track
- Developer Tool

**Comment by zxstim** [comment]
Approved. Given this is a developer tool, I expect that you go beyond their docs to help other devs with a good starting out template
- you need good docs inside your tool, use the `README.md` file or make a whole `docs` folder.
- Clear comments, explain the thought process
- 3 keys questions to answer:
  - what is this?
  - why use this?
  - how to use this?

**Comment by PaulElisha** [comment]
This proposal shows how to build cross-chain applications, it contains code templates that demonstrates the process from start to finish. Also, it shows how to leverage the oft standard of layer zero to build cross-chain tokens that unifies liquidity.

Why this proposal?

It shows developers how to leverage the layer zero standard to build tokens that are cross-chain compatible ensuring liquidity movement from one chain to Kaia chain and establishing a global ledger.

It shows developers how to build applications using layer zero, leveraging on layer zero endpoint for kaia to send cross-chain messages from a chain to kaia.

In the code is a template of a smart contract that was used to update the state of an application from Sepolia on the kaia chain.

Developers can use this knowledge to build DeFi projects or applications that ensure easy access of liquidity from any chain to kaia.

Issue: https://github.com/kaiachain/kaia-dapp-mono/issues/200

Build: https://github.com/PaulElisha/lz-cross-chain-project

Dorahack: https://dorahacks.io/buidl/18257

**Comment by zxstim** [comment]
Approved `1500 KAIA` bounty

**Comment by zxstim** [comment]
Closing
