### ISSUE TITLE
Proposal: Youtube Free Course on How to make a blockchain game on KAIA

### ISSUE THREAD

**Issue by KelvinTrinhSG** [kaiachain/kaia-dapp-mono#210]
Description:

- This submission is a comprehensive and FREE **Udemy** course designed to teach developers how to build blockchain-integrated games on the KAIA blockchain.
- The course provides a step-by-step guide, from setting up a development environment and integrating blockchain functionalities to deploying a game on KAIA.
- With easy-to-follow lessons, this course empowers both beginners and experienced developers to leverage KAIA’s unique features for fast and low-cost in-game transactions.
- Students will learn practical game development skills using Unity and KAIA’s blockchain technology, culminating in a fully functional blockchain game by the course's end.

Bounty track
- Education

**Comment by zxstim** [comment]
No Udemy course sorry. 

Just make a repository on your github with all the notes in `.md` files. Attach links to Youtube videos, references.

Anyway, love it. I will learn something too. Teach me sensei.

**Comment by KelvinTrinhSG** [comment]
Hi @zxstim 

I’ve just completed the "Develop Blockchain Game on Kaia" course! It took me over a week of day and night work to put everything together using Clipchamp and AI Tool ElevenLabs.io, along with Unity SDK and Thirdweb Unity SDK for a thorough learning experience.
I’d really appreciate your review and support to help the course reach more people. Please feel free to reach out if you need any additional details!

Github Repository: https://github.com/KelvinTrinhSG/Develop-Blockchain-Game-On-Kaia-Course

Thank you so much!

**Comment by zxstim** [comment]
will get the intern to tweet about this

**Comment by KelvinTrinhSG** [comment]
Hi @zxstim 

Thank you so much for your support.
If you have any further requests, please let me know.
If everything necessary has been addressed, can we close this issue?

Thank you so much!

**Comment by zxstim** [comment]
Hey i just got back from devcon. Will assign bounty today. You will see the noti.

**Comment by KelvinTrinhSG** [comment]
Hi @zxstim 
I know you are super busy.
But I am still waiting for your noti, bro.

**Comment by zxstim** [comment]
Well made. I would prefer a harder game though. Approved for `1500 KAIA` bounty.

My recommendation for next submission is making a starter game and make the videos. Like a more complete game with some unique mechanics like NFT and tokens.

**Comment by zxstim** [comment]
Closing for payout
