### ISSUE TITLE
Proposal: [Follow-up on Submitted Bounty for Kaia P2P Escrow Platform]

### ISSUE THREAD

**Issue by Emmanueltech** [kaiachain/kaia-dapp-mono#211]
Description
- [Hey there victor,
I claimed the bounty on 28th Oct https://github.com/kaiachain/kaia-dapp-mono/issues/146 but haven’t received any feedback yet. I wanted to confirm if there’s anything else needed to move this forward. I’m looking forward to any updates and am happy to adjust the work if necessary. 
Let me know 
-Emmanuel 
]

Bounty track
- [Issue]

**Comment by Emmanueleclipse** [comment]
@zxstim it's the an escrow system for trading Kaia, securely holding assets until both buyer and seller fulfill their obligations, while also serving as an onramp and offramp for Kaia by allowing users to convert fiat currency to Kaia and vice versa (providing an easy way to acquire Kaia from other users

**Comment by Emmanueltech** [comment]
@zxstim I pinged you more than once, I had to reply to this after I got no reply.
