### ISSUE TITLE
Proposal: Guide on creating Subgraph with Graph on Kaia

### ISSUE THREAD

**Issue by anudeep11k** [kaiachain/kaia-dapp-mono#212]
Description
- A detailed guide on creating your First SubGraph on Kaia
- A simple useful example 

Bounty track
- Kaia Fall-Odyssey

Github repo : https://github.com/anudeep11k/kaia-subgraph
Here is the full guide and Subgraph example : https://github.com/anudeep11k/kaia-subgraph/blob/main/README.md
And Subgraph Code : https://github.com/anudeep11k/kaia-subgraph/tree/main/subgraph

Here is the link for subgraph https://thegraph.com/studio/subgraph/subgraph-kaia

**Comment by zxstim** [comment]
Nice. Approved and will mark as `submitted`. Ping me regularly (every few days) because i forget sometimes.

**Comment by zxstim** [comment]
Will check on this ASAP

**Comment by anudeep11k** [comment]
Thanks. For your info, i already built it. Done 
Please let me know further steps

**Comment by anudeep11k** [comment]
Hey team iam hoping a reply from you

**Comment by anudeep11k** [comment]
Hey @zxstim whats the update on this ?

**Comment by zxstim** [comment]
Hey, as I am not super used to Subgraph, I need a few days to go over the  graph docs/examples/etc.

Feel free to open a new proposal and keep building

**Comment by anudeep11k** [comment]
Hey any update regarding this submission?

**Comment by anudeep11k** [comment]
Hey @zxstim any update regarding this submission ?

**Comment by zxstim** [comment]
Hi. Just made it back from Devcon. Will assign bounty to this today and payout.

**Comment by anudeep11k** [comment]
Hi i hope you had a great time at devcon
Me Missed it ! 
Looking forward regarding submission

**Comment by zxstim** [comment]
Approved for `1500 KAIA` bounty payout.

**Comment by zxstim** [comment]
If you can, I suggest your next submission would be building a subgraph for [dgswap.io](https://dgswap.io/)

**Comment by zxstim** [comment]
Also, turn your subgraph link public (it's private maybe)

**Comment by zxstim** [comment]
Closing for payout

**Comment by anudeep11k** [comment]
Thanks, @zxstim, for the bounty. I just published the Subgraph. 
I will start developing a new subgraph on dgswap.io.
Acknowledgement: I confirm the below address is my bounty payout address. Payout address: 0x428C70237C612d551047D9671c25C360ae4BBfA3

**Comment by zxstim** [comment]
Follow this

https://dorahacks.io/hackathon/kaia-fall-odyssey/detail#submission-guidelines

**Comment by anudeep11k** [comment]
https://dorahacks.io/buidl/20033
hey @zxstim please check my above BUIDL submission and let me if anything else needed
Thanks

**Comment by anudeep11k** [comment]
Hey @zxstim any update ? Regarding bounty or my buidl submission i still see under review
