### ISSUE TITLE
Proposal: Discussing Kaia on Binance Live

### ISSUE THREAD

**Issue by ayo-klaytn** [kaiachain/kaia-dapp-mono#215]
**Description**

* Small trial rewards for Binance Live participants
* Share insights into Kaia, builder grant program, and various community initiatives.

Note:
Opened issue for tracking purpose

**Bounty track**
* Community

**Comment by zxstim** [comment]
Approved for `450 KLAY`. Take a screenshot and post here for tracking.

**Comment by ayo-klaytn** [comment]
Here is a link to the [Binance Live](https://www.binance.com/en/live/video?roomId=2231031) and [X post](https://x.com/elgeod/status/1849418010072944833)

Attached below is the screenshot of event stats.

![bl-kaia](https://github.com/user-attachments/assets/f4328f31-74b9-4b06-8a40-d53b7ca8a889)
