### ISSUE TITLE
Proposal: Kaia twitter space with CryptoForte community.

### ISSUE THREAD

**Issue by oxmichaeljerry** [kaiachain/kaia-dapp-mono#216]
Description
- A virtual event (Telegram AMA) to educate our community of over 2000 members mostly Africans(Developers and Non-Devs) about KAIA chain, L1, L2, products and platforms on Kaia like kaiafun for degenerate, traders as well as building, deploying and on Kaia and participating in KAIA bounties and ecosystem.

CryptoForte links. 
Twitter: https://x.com/thecryptoforte
Telegram: https://t.me/thecryptoforte
LinkedIN: https://www.linkedin.com/company/cryptoforte/about/
YouTube: https://www.youtube.com/channel/UCSSiT4NuCSeC-2Hgiz9ADSw

I intend to collaborate with 0Xpampam for the virtual event.

Bounty track
- Education and community.

**Comment by zxstim** [comment]
Approved. Don't forget to make Dorahacks BUIDL.

tagging @ayo-klaytn as reminder

**Comment by oxmichaeljerry** [comment]
The space has been completed, we had over 380 persons tuned in to listen. https://x.com/thecryptoforte/status/1857055990538993863

Here is the link to the announcement. https://x.com/thecryptoforte/status/1857056266121597146

Thank you so much, looking forward to next adventures with KAIA. @zxstim @ayo-klaytn

**Comment by zxstim** [comment]
Approved for an extra `380 KAIA` for you. You can make use of the amount to incentivize your community.

**Comment by zxstim** [comment]
closing
