### ISSUE TITLE
Proposal: Onchain Educational Games

### ISSUE THREAD

**Issue by Lou1sVuong** [kaiachain/kaia-dapp-mono#220]
Description
- Educational games built on the blockchain that reward players with tokens for completing educational challenges, promoting learning in a fun and engaging way.

Bounty track
- Education

**Comment by zxstim** [comment]
Can you make it as puzzles? Like how to hack this contract (https://ethernaut.openzeppelin.com/), or figure out how to change a value without changing the contract (https://github.com/alchemyplatform/Contract-Puzzles)

I don't want to see things like "what is Kaia with 4 possible answers and 1 correct". Need to be challenging to be worth the effort of building it.

**Comment by 0xLou1s** [comment]
> Can you make it as puzzles? Like how to hack this contract (https://ethernaut.openzeppelin.com/), or figure out how to change a value without changing the contract (https://github.com/alchemyplatform/Contract-Puzzles)
> 
> I don't want to see things like "what is Kaia with 4 possible answers and 1 correct". Need to be challenging to be worth the effort of building it.


I have prepared a rough interface in your favorite style, including quizzes, after receiving your feedback, the next part I will integrate connected wallets and smart contracts

Check here : https://kaialearn.vercel.app/ , click on "Try It Out" to see the puzzles interface

**Comment by zxstim** [comment]
yo the site is bussin. but focus on the contents, the UI can come in the next update submission.

**Comment by 0xLou1s** [comment]
I have update for this proposal @zxstim 

Dorahack : https://dorahacks.io/buidl/20029
Demo Video : https://youtu.be/zeD-9DKsZqM
Source code : https://github.com/Lou1sVuong/kaialearn
Smartcontract mint nft : https://github.com/Lou1sVuong/smartcontract-kaialearn-mintnft

**Comment by 0xLou1s** [comment]
@zxstim sr for ping you again

**Comment by zxstim** [comment]
hey sorry. Approved for `2200 KAIA` payout. Great work. Actually look nice. I want to use this for our bootcamp

**Comment by zxstim** [comment]
closing for payout. do note that we are waiting for dorahacks to top up the prize pool

**Comment by 0xLou1s** [comment]
thank you much. If possible, please give me your feedback or suggest additional ideas or features that need to be developed to make my project more complete ^^

> hey sorry. Approved for `2200 KAIA` payout. Great work. Actually look nice. I want to use this for our bootcamp

**Comment by zxstim** [comment]
Updated the payout amount due to mispayment issue (adjusted to today's price)

`1700 KAIA`

**Comment by moonfury-ops** [comment]
Hello @0xLou1s 
Could you give me chance to work with you?

**Comment by 0xLou1s** [comment]
> Hello [@0xLou1s](https://github.com/0xLou1s) Could you give me chance to work with you?

yep, check contact me here : [lou1s.fun](https://www.lou1s.fun/)
