### ISSUE TITLE
Proposal: Follow-up on Submitted Bounty for Kaia P2P Escrow Platforml]

### ISSUE THREAD

**Issue by Emmanueltech** [kaiachain/kaia-dapp-mono#221]
Description
- [dHey there victor,
I claimed the bounty on 28th Oct https://github.com/https://github.com/kaiachain/kaia-dapp-mono/issues/146 but haven’t received any feedback yet. I wanted to confirm if there’s anything else needed to move this forward. I’m looking forward to any updates and am happy to adjust the work if necessary.
Let me know
-Emmanuel

Bounty track
- [add the name of the bounty track here]

**Comment by zxstim** [comment]
One more spam issue and I will disqualify your submission immediately.

**Comment by Emmanuel3232999** [comment]
@zxstim alright, can you however respond so we can resolve this in a more collaborative manner

**Comment by Emmanuel3232999** [comment]
@zxstim I don't want to be one of those people who set up a bot to spam your github, or worse. Let's be collaborative. Thanks
