### ISSUE TITLE
Proposal: A dedicated KaiaScan SDK in Go

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#237]
Description
- This proposal outlines the need for a dedicated KaiaScan SDK in Go, detailing its benefits and functionalities. KaiaScan, a blockchain explorer specifically designed for the Kaia ecosystem, provides real-time data tracking and insights into token movements, transactions, and more.

- Core functionalities:
 Token information retrieval
 Transaction tracking
  Block information
  Contract Interaction
  
- Why proposal?
  It simplifies the integration of kaiascan functionalities into application.
  It encapsulate api calls making it a user-friendly approach to access kaia blockchain information.
  Enhanced developer experience

Bounty track
- Developer tool

**Comment by PaulElisha** [comment]
Done.

Github Link: https://github.com/PaulElisha/kaiascan-sdk-go
Dorahack: https://dorahacks.io/buidl/19153

**Comment by zxstim** [comment]
Approved for `1500 KAIA` payout

**Comment by zxstim** [comment]
closing
