### ISSUE TITLE
Proposal: Kaia Connect: Coffee & Code Conversations

### ISSUE THREAD

**Issue by Marlon-id** [kaiachain/kaia-dapp-mono#239]
Description:
Marlon (Brand Ambassador) and Erick (Developer Ambassador) of Kaia Chain are moving forward with plans to host small-scale meetups in Pontianak, Indonesia, at a local coffee shop. We aim to have 7-9 attendees per session, but we are now requesting to accommodate more participants, such as an entire class in the SMK Immanuel Pontianak (Immanuel Vocational Highschool), Indonesia and Institute Technology and Business Sabda Setia Pontianak, but we still waiting for the acceptance from the teachers and lecturers to conduct there. These meetups will create a friendly space for attendees to learn about Web 3 concepts and gain an introduction to Kaia Chain.

Our goal is to facilitate discussions about blockchain fundamentals, share insights, and foster community connections in a relaxed, open environment that encourages conversation and networking. To show appreciation, participants will receive Kaia Chain merchandise. However, we wish to inform the KAIA Team that, unlike the Vietnam meetup, we will not have a Kaia Chain banner for this event.

**Comment by zxstim** [comment]
Cool. Approved but can you modify the proposal to be for each meetup.

For example, i plan a meetup on x date at y location. then post photos on social to claim.

make sure you open a BUIDL on dorahacks too.

**Comment by Marlon-id** [comment]
Estimation Cost:
1. Print a Standee Banner with size 60x160cm : 15USD (Albatros Banner Quality), Design is provided below... 
    ![Frame 2](https://github.com/user-attachments/assets/9216fbb4-0250-4ea2-a213-c6e4c2ddf7a4)
2. Drink for 30 Institute of Technology Sabda Setia Students (We providing 250ml milk with each cost around 0.63 USD) : 19.02 USD 
3. Rough Grand Total for this first session : 34.02 USD 

Location: 
https://maps.app.goo.gl/yZXFEcVuYyLZ8p3X7

Date Time: 21 November 2024, 08:30 ~ 09:40 West Indonesia Time

**Comment by zxstim** [comment]
Pre-approve $15 (`120 KAIA`) for banner printing

**Comment by Marlon-id** [comment]
![image](https://github.com/user-attachments/assets/cd6c0f4b-3846-47f9-b178-c22be4a3b275)
Banner has been printed out successfully~

**Comment by Marlon-id** [comment]
![image](https://github.com/user-attachments/assets/cd6c0f4b-3846-47f9-b178-c22be4a3b275)
Banner has been printed out succesfully~

**Comment by Marlon-id** [comment]
Update Estimation Cost:
1. Drink for 40 Institute of Technology Sabda Setia Students and Lecturers (We providing 250ml milk with each cost around 0.30 USD) : 12.13 USD
2. Drink + Snacks for 14 Immanuel Vocational Highschool Students and Teachers in La Vica Cafe (Local nearby coffee shop): roughly cost around 30 USD

**Comment by Marlon-id** [comment]
Documentation for Kaia Hangouts with Immanuel Vocational Highschool students and Teachers!
![WhatsApp Image 2024-11-20 at 20 33 15_176b735e](https://github.com/user-attachments/assets/441047fe-2d5e-4b9c-bf2e-1cbf6975a842)
Total spending for drinks and snacks cost for IDR 416.000, roughly USD 26.5

**Comment by Marlon-id** [comment]
Documentation for Kaia Hangouts with Institute Technology and Business Sabda Setia Students and Lecturers!
![image](https://github.com/user-attachments/assets/3bd93ad9-3532-44be-ac5c-74aa0c912e2a)
Total spending for drinks cost for IDR 192.000, roughly USD 12.1

**Comment by Marlon-id** [comment]
Total spending for Drinks and Snacks for the 2 session is 
 12.1 USD + 26.5 USD = 38.6 USD

**Comment by zxstim** [comment]
Approved for `850 KAIA` bounty.

**Comment by zxstim** [comment]
closing
