### ISSUE TITLE
Update: Article and code docs explaining layer zero inner workings and technical steps on building a cross-chain application.

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#240]
Description
- The update is a detailed beginner friendly explanation that covers the inner workings and low-level mechanisms of how layer zero performs cross-chain messaging.
- It contains technical details on building cross-chain applications.

Reference issue
- #200 

Category
- Developer Tool

**Comment by PaulElisha** [comment]
Done: https://github.com/PaulElisha/lz-crosschain-template/blob/main/article/article.md

**Comment by zxstim** [comment]
Approved `1200 KAIA` for docs improvement.

**Comment by zxstim** [comment]
Closing
