### ISSUE TITLE
Proposal: Kaia Community Workshop at Cafe One, Lagos, Nigeria.

### ISSUE THREAD

**Issue by afrokayie** [kaiachain/kaia-dapp-mono#243]
Description
- This Community Workshop will be held at Café One in Yaba, Lagos, Nigeria. It will serve as an in-person event designed to introduce the Kaia blockchain and highlight Kaia's latest initiatives, including the Kaia Wave campaign.

I will collaborate with @Oxpampam and the workshop will focus on driving blockchain adoption through consumer applications and showcasing how Kaia’s ecosystem can empower developers to build decentralized applications (DApps) seamlessly. Attendees will gain insights into Kaia’s tools, resources, and support systems, which will enhance innovation and help builders create impactful projects on the Kaia platform.

This is an ideal opportunity for developers, blockchain enthusiasts, and entrepreneurs to explore how Kaia can be a foundation for their next project.

Bounty track
- Education and Community.

**Comment by zxstim** [comment]
Approved. Budget wise:
- you will get a small allocation for your effort and travel
- attendees will get from 5-10 KAIA to try out mainnet
- drinks are covered

**Comment by afrokayie** [comment]
Thank you. Here are the budget details:

- Cafe One Usage - $12 per hour X 3 = $36
- Projector - $10 per hour = $30
- Event banner & awareness set up = $25 + $15 = $40
- Logistics - $20
- Pastry and coffee (minimum of 50 people) - $100
- 2 Speakers welfare &amp; transport - $50

- Total === $276

**Comment by ayo-klaytn** [comment]
@zxstim we can proceed with this proposal.  I will work on execution with @afrokayie

**Comment by zxstim** [comment]
Pre-approve 40 + 36 + 100 = $176 (`1322 KAIA`) for prep.

**Comment by afrokayie** [comment]
Hello, the Kaia Community Workshop has been completed as of November 29th. We had a gathering of builders that explored Kaia ecosystem and the infrastructures, and opportunities available. Here's a link to our X announcement: [twitter post](https://x.com/afrokayie/status/1863561039838593033)

Event pictures are available here [event pictures](https://drive.google.com/drive/folders/17KyRtfpfCi141eG4LnvUslM_GZwa3-gx)

<img width="868" alt="Screenshot 2024-12-02 at 14 38 34" src="https://github.com/user-attachments/assets/9acf5c3c-30eb-4090-9112-9414bffebc70">

**Comment by zxstim** [comment]
Approved for `300 (remaining budget) + 150 (airdrop to attendees; 10 KAIA each) = 450 KAIA`

**Comment by zxstim** [comment]
closing for payout
