### ISSUE TITLE
Indexing Data On KaiaChain With Subgraph

### ISSUE THREAD

**Issue by CoderOfPHCity** [kaiachain/kaia-dapp-mono#244]
Description
- A complete tutorial on indexing data and query with subgraph cli query
- Advanced step by step guide to setup subgraph event handlers on the klaytn DAI contract address in kaiachain explorer.
- Query events and publishing a subgraph directly from kaia blockchain and concise guide on subgraph deployment.

Bounty track
- Developer tools
- Kaia Fall-Odyssey

Article Markdown Link: https://hackmd.io/NNiNT0muT0CG8t19kMM_WQ?view
GitHub Tutorial Code: https://github.com/CoderOfPHCity/GraphQL-Subgraph-Query

Dorahack: https://dorahacks.io/buidl/19618

**Comment by zxstim** [comment]
Alright. Checking.

**Comment by zxstim** [comment]
Approved for `1500 KAIA` bounty. Can you copy and paste the dorahacks BUIDL link here?

**Comment by zxstim** [comment]
Closing

**Comment by CoderOfPHCity** [comment]
https://dorahacks.io/buidl/19618

Thanks
