### ISSUE TITLE
Proposal: Kaia Multiplayer Shooter Game: Dive into the Blockchain-Powered Battleground!

### ISSUE THREAD

**Issue by trandrewsg91** [kaiachain/kaia-dapp-mono#246]
**Description**

Join the action in a multiplayer arena where 2-8 players can compete in thrilling, Kaia blockchain-integrated gameplay.

- Bet to Win: Each player places a 1 KAIA bet before the match begins. The winner takes it all, claiming the entire KAIA prize pool!
- Fast-Paced Rounds: Each game is an intense 3-minute showdown, pushing players to give their best in a limited time.
- Secure Transactions: Powered by a smart contract factory, each match creates a unique escrow contract to securely hold players' funds. At the end of each game, the escrow automatically transfers the prize to the winner.

Video:
https://www.youtube.com/watch?v=CtwiBV9kMhI

Game:
https://trandrewsg91.itch.io/kaia-multiplayer-shooter-game

Github:
https://github.com/trandrewsg91/Bloody-Hunter-Multiplayer-Shooting-Game-On-KAIA

Twitter:
https://x.com/TranDrew251678/status/1856339219398177300

**Bounty track**
- others, Game

**Comment by zxstim** [comment]
Approved and marked as `submitted`.

**Comment by trandrewsg91** [comment]
Hi @zxstim 
I have created the build on Dorahack
https://dorahacks.io/buidl/20028

May I ask if I need to do anything else or could we proceed to the next step.

Thanks.

**Comment by trandrewsg91** [comment]
**New Update!**
I add NFT Shop into the game.

So this game has 2 main features:
1. NFT shop for players to buy and upgrade their character.
2. Betting 0.2 KAIA for each game. Winner takes all.
3. Have from 2 to 8 players playing together in a game room.

Have fun playing this game.
Thanks

![NFT Shop](https://github.com/user-attachments/assets/95d0a439-be63-4127-996d-5c0f05e80690)

**Comment by trandrewsg91** [comment]
@zxstim 
Thank you so much for your support.
Could you please support to review this game?
Thanks Bro.

**Comment by zxstim** [comment]
Looks great. Approved for `2200 KAIA` bounty. Pending pool top up from dorahacks for payout btw.

**Comment by zxstim** [comment]
Closing
