### ISSUE TITLE
Update: Improved smart contract inspect tool

### ISSUE THREAD

**Issue by haxxstig** [kaiachain/kaia-dapp-mono#249]
Description
- Improved UX
- Added my contract book to revisit later
- Added support for Kaia

Reference issue
- #2 

Category
- Developer tools. Categories are here: https://dub.sh/7zwejAg

**Comment by zxstim** [comment]
Approved to proceed. Revert back with implementation.

**Comment by haxxstig** [comment]
Link: https://www.blockcmd.com/inspect
Github: https://github.com/blockcmd/blockcmd-app

**Comment by zxstim** [comment]
Approved `2500 KAIA` for UX improvement

**Comment by zxstim** [comment]
closing
