### ISSUE TITLE
Proposal: DeFi calculator for DEXs

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#25]
## Description
A DeFi calculator with the following features: 
- track your entry price
- real profit (fees + rewards minus IL)
- auto calculate range quickly to add liquidity

## Bounty track
- DeFi

**Comment by zxstim** [comment]
Much needed tool for LPs. Approved to proceed.

**Comment by haxxsniper** [comment]
Submitting my implementation here:
https://dexcmd.com

Repo:
https://github.com/blockcmd/dexcmd

**Comment by zxstim** [comment]
Approved `1500 KLAY` payout. Well made calculator.
