### ISSUE TITLE
Proposal: A dedicated kaiascan SDK in rust

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#250]
Description

This proposal outlines the need for a dedicated KaiaScan SDK in Go, detailing its benefits and functionalities. KaiaScan, a blockchain explorer specifically designed for the Kaia ecosystem, provides real-time data tracking and insights into token movements, transactions, and more.

Core functionalities:
Token information retrieval
Transaction tracking
Block information
Contract Interaction

Why proposal?
It simplifies the integration of kaiascan functionalities into application.
It encapsulate api calls making it a user-friendly approach to access kaia blockchain information.
Enhanced developer experience

Bounty track

Developer tool

**Comment by zxstim** [comment]
Approved to proceed.

**Comment by PaulElisha** [comment]
Done: https://dorahacks.io/buidl/20040
Github: https://github.com/PaulElisha/kaiascan-sdk-rs

**Comment by zxstim** [comment]
Approved for `1500 KAIA` bounty

**Comment by zxstim** [comment]
closing
