### ISSUE TITLE
Proposal: Kaia Community Workshop at Opolo Tech. Hub, Bayero University, Kano.

### ISSUE THREAD

**Issue by 3ppleA** [kaiachain/kaia-dapp-mono#251]
Description
- **Kaia Community Workshop at Opolo Tech. Hub, Bayero University, Kano.**

This Kaia workshop will be held on Tuesday, December 10, at Opolo Tech Hub, Bayero University Kano (New Campus). We intend to collaborate with @Oxpampam as a speaker for the workshop.

 We’re bringing together developers, content creators, graphics designers, newbies, and allies from across different ecosystems to gain insights into the exciting world of Kaia!

 **The workshop will feature:**
-Overview of Kaia Ecosystem
-DeFi opportunities on Kaia
-Mainnet/ Testnet testing 
-Ongoing campaigns
-Kaia wallet downloads
-Networking & onboarding session
-Free drinks and snacks
-Games
And lots more…

BUDGET:
Opolo Tech Hub (Hall, Sound system, Projector) for a day event - $50
Event banner - $25
Banner set-up -  $20
Logistics - $20
Pastry and coffee for attendees - $100
Speakers welfare & transport - $50

Total === $265

Others
-$KAIA distribution to attendees- $

Bounty track
- Education

----
Acknowledgement: I confirm the below address is my bounty payout address.
Payout address: 0x0baa69b3e32d5eae62c8f1a053f23fbdd4670cf7

**Comment by zxstim** [comment]
Check this for me @ayo-klaytn

**Comment by ayo-klaytn** [comment]
Yeah for sure. I ll be working with @3ppleA on this.

Might need to update the budget: 
* Other items stated in the budget
* Pastry and coffee for attendees - $75
* Speakers welfare & transport - $25

New Total = $215

**Comment by 3ppleA** [comment]
Alright, well-noted ser.

**Comment by zxstim** [comment]
Approved. Please proceed.

**Comment by 3ppleA** [comment]
We have just completed Kaia Community Workshop at Opolo Tech. Hub, Bayero University, Kano.
https://x.com/DefiKing_001/status/1868984741657268647
![Uploading KAIA IMG_2280.jpeg…]()
![image](https://github.com/user-attachments/assets/40205d16-5210-4a31-b316-a256bffe1efd)


@zxstim @ayo-klaytn

**Comment by zxstim** [comment]
what's your dorahacks BUIDL?

**Comment by zxstim** [comment]
approved for `900 KAIA cost + 125 KAIA personal comp = 1025 KAIA`

**Comment by zxstim** [comment]
closing

**Comment by 3ppleA** [comment]
@zxstim here's my wallet address. 

0x0baa69b3e32d5eae62c8f1a053f23fbdd4670cf7

**Comment by zxstim** [comment]
must be Dorahacks BUIDL based on guidelines below

https://dorahacks.io/hackathon/kaia-winter-epoch/detail#submission-guidelines

**Comment by 3ppleA** [comment]
Alright, I've added it to the BUIDL @zxstim

**Comment by zxstim** [comment]
what BUIDL number?

**Comment by 3ppleA** [comment]
@zxstim I can't find the BUIDL number but link to the submission on DoraHacks: https://dorahacks.io/buidl/20905
