### ISSUE TITLE
Proposal: permit2-integration-template

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#253]
Description
- This is a developer tool, a template that explains the integration of permit2 for kaia developers to easily integrate permit2 in their codebase.
- It enables kaia developers to leverage the possibilities of permit2 to build DeFi applications that improve user experience.
- It contains an article that explains the architectural overview of the protocol.

Bounty track
- Developer tool

**Comment by PaulElisha** [comment]
Dorahack: https://dorahacks.io/buidl/20054
Repo: https://github.com/PaulElisha/permit2-test-integration

**Comment by zxstim** [comment]
Approved for `2000 KAIA` bounty.

**Comment by zxstim** [comment]
Closing for payout
