### ISSUE TITLE
Proposal: Exploring-Foundry-Cast-for-Kaia-Blockchain-A-Developer-s-Guide

### ISSUE THREAD

**Issue by detty-dev** [kaiachain/kaia-dapp-mono#255]
Description
This article explores Foundry Cast, its functions, and, through practical examples, how you can apply it to Kaia Blockchain development.

https://github.com/detty-dev/Exploring-Foundry-Cast-for-Kaia-Blockchain-A-Developer-s-Guide/tree/Exploring-Foundry-Cast-for-Kaia-Blockchain-A-Developer-s-Guide

Bounty track
- Developer Tooling

**Comment by zxstim** [comment]
Actually well written about cast. Need you to fix any part using `--private-key` flag and change to `--account` flag from foundry.

NEVER LEAVE PRIVATE KEY IN `.ENV` FILE!

**Comment by detty-dev** [comment]
Noted with thanks. I truly appreciate the valuable insight

Done

**Comment by zxstim** [comment]
I don't see the updates in the repo
https://github.com/detty-dev/Exploring-Foundry-Cast-for-Kaia-Blockchain-A-Developer-s-Guide

Do you use a fork of this mono repo? You can switch to the above repo now. No need for the PR.

**Comment by detty-dev** [comment]
The repo is mine and it's not a PR

**Comment by PaulElisha** [comment]
@detty-dev the update is fixing any part using cli private key flag (--private-key) and using account flag (--account). Kindly go through your repo and make necessary changes.

**Comment by detty-dev** [comment]
I have done that, kindly check

**Comment by PaulElisha** [comment]
```bash
cast send --rpc-url https://rpc.kaia.network --account YOUR_PRIVATE_KEY --to 0xRecipientAddress --value 1000000000000000000  # 1 Kaia token in the smallest unit (wei)
```

so I think if you fixed it, then the account parameters should be used and not "YOUR_PRIVATE_KEY". Did you test it to confirm the cli parameters are correct?

Also here:

```bash
cast chain-id --rpc-url https://testnet.kaia.io/rpc
```

Kindly replace all testnet or Mainnet rpc-url to Kaia's original testnet/mainnet JSON RPC Endpoints ([see kaia docs](https://docs.kaia.io/references/public-en/)). The same applies to chainid, if you have interacted with kaia before, chainid are 1001 and 8217 respectively.

The output of your cast commands has no relationship with your cli inputs, kindly fix that too.

Lastly, private key is still being used on this line:

```bash
cast send --rpc-url https://rpc.kaia.network --private-key YOUR_PRIVATE_KEY --to 0xTokenContractAddress --data "0xa9059cbb000000000000000000000000RecipientAddress0000000000000000000000000000000000"
```

Go through everything and fix them. 

Bear in mind that @zxstim approves contents that are technical, comprehensive, follows the rules of open-source and well-tested if they contain codes.

**Comment by detty-dev** [comment]
All has been corrected, kindly check @PaulElisha @zxstim

**Comment by PaulElisha** [comment]
Of the 4 updates, I didn't see any. 

1. The output of your cast command should have a relationship with the command.

e.g. you entered this command:

```bash
cast chain-id --rpc-url https://testnet.kaia.io/rpc
```

You most likely didn't run this command in your CLI because you were supposed to use Kaia Kairos testnet rpc, which is (https://public-en-kairos.node.kaia.io), [see kaia docs](https://docs.kaia.io/references/public-en/)

So, make the output reflect that you run test run this command.

Your output: 67890
Kaia Kairos chainid: 1001

2. Kindly follow the principles of open-source, this doesn't look like a carefully crafted article. Focus on a quality article as it's meant to ensure developers can interact with the Kaia chain simply by reading your article.

3. You are not using the --account flag parameters because you are still using "private key"

```bash
cast send --rpc-url https://rpc.kaia.network --account YOUR_PRIVATE_KEY --to 0xRecipientAddress --value 1000000000000000000  # 1 Kaia token in the smallest unit (wei)
```

Pls, correct everything.

**Comment by detty-dev** [comment]
All correction done @PaulElisha kindly check

**Comment by PaulElisha** [comment]
okay, good one. 

cc: @zxstim

**Comment by PaulElisha** [comment]
@detty-dev Below are some of your cast commands you should correct.

1. Remove the closing bracket for it to run.
```bash
paulelisha@Macbook-M3-Pro ~ % cast chain-id --rpc-url https://public-en-kairos.node.kaia.io)
zsh: parse error near `)'
```

2. This returns unknown, kindly fix it.
```bash
paulelisha@Macbook-M3-Pro ~ % cast chain --rpc-url https://public-en-kairos.node.kaia.io
unknown
```

**Comment by detty-dev** [comment]
Duly noted

**Comment by PaulElisha** [comment]
revert when you are done.

**Comment by detty-dev** [comment]
Done

**Comment by PaulElisha** [comment]
Submit a screenshot of what you run and the output

**Comment by detty-dev** [comment]
Below is the screenshot for the test

The other test has been removed from my article due to incompatibility with Kaia

(https://github.com/user-attachments/assets/ef3acf94-0f6d-4a9c-9ff1-29420813c8c0)

**Comment by detty-dev** [comment]
Below is the screenshot for the test

The other test has been removed from my article due to incompatibilities with Kaia

(https://github.com/user-attachments/assets/ae377486-e5f3-4154-bafe-436cd304fa46)

@PaulElisha @zxstim

**Comment by PaulElisha** [comment]
Okay.

Cc: @zxstim

**Comment by zxstim** [comment]
Approved for `420 KAIA with 50% penalty = 210 KAIA`

get active online to claim the 50% penalty on next submission

https://x.com/KaiaDevIntern/status/1866841240433725729

**Comment by zxstim** [comment]
closing
