### ISSUE TITLE
Offline Kaia Community Workshop at Adeyemi Federal University of Education, Ondo State, Nigeria. 

### ISSUE THREAD

**Issue by samlovework** [kaiachain/kaia-dapp-mono#257]
Description

- The Community Workshop will be a physical event and take place at the School event Hall, at Adeyemi Federal University of Education, Ondo State, Nigeria. 

The workshop is about introducing Blockchain Technology, introducing Kaia blockchain, kaia mission and uniqueness in the Web3 space.

In addition, how Kaia can help builders to build Dapp on Kaia, how Non-tech Web3 enthusiasts, writers can contribute to kaia blockchain and a community can be started after the event.

I intend to speak and collaborate with  @PaulElisha as a dev speaker for the workshop. 
The Workshop will take place on Saturday, 7th of December, 2024.

BUDGET:

Event Hall - $25
Standee Banner for subsequent events with size 60cm * 160cm: $50
Event Banner & set-up - $20
Sound system — $10
Projector— $10
Logistics - $20
Pastry and coffee for attendees - $85
Speaker @PaulElisha welfare & transport expenses - $20

Total === $240

Others
-$KAIA distribution to participants- $

Bounty track
- [Education and Community]

**Comment by ayo-klaytn** [comment]
@zxstim LKGTM.  We can proceed for sure

**Comment by zxstim** [comment]
Approved to proceed but I don't want anymore big events after this one. If you need pre-payment to execute, then the event is beyond your capability.

I prefer small coffee meetups (less than 10 people) that can come and build something for this builder program or for the general community to engage in fun activities.

**Comment by samlovework** [comment]
Noted with thanks.

We will work on small coffee meetups with builders after this event.

We've also on-boarded devs and non-devs in the Kaia Africa Online Community from the previous events.

They are presently getting free mentorship and learning all about KaiaChain at the moment.

Thank you.

**Comment by zxstim** [comment]
so in regards to onboarding, i need people to do something for me to know they are onboarded and contributing. Crypto is all about community and how can we empower said community.
- For developers, they can join this builder program to contribute and earn (tons of things to build)
- For creators, they can create NFTs, memes, host online spaces/meetups and make contents. @kaia-dev-intern will be tipping people onchain.
- For just community members, they can try out all the dapps on kaia, write their feedbacks, make tutorials, help others to get onboarded by posting contents on social media. @kaia-dev-intern will see and tip them.

**Comment by samlovework** [comment]
These are great opportunities for us in our community, I've passed the information to community members including devs and creators.

@ayo-klaytn and @PaulElisha will help monitor their contributions.

Thank you.

**Comment by samlovework** [comment]
Hello, the Kaia Community Workshop has been completed as of December 7th. We had a gathering of builders (devs and non-devs) that explored the Kaia ecosystem, the infrastructures and opportunities available.

Here is the link to our X announcement.

[([(https://x.com/samlovework/status/1866120636763983877?t=jrpVgiWNQSN_ZZ_HYIyn6Q&s=19))]

Events pictures below:
![IMG_20241209_144745_432](https://github.com/user-attachments/assets/75dad653-8955-4583-8789-35612310bd5a)
![IMG_20241207_130930_966](https://github.com/user-attachments/assets/92d846e8-5805-4ff1-aad4-f3c9588fa838)
![IMG_20241209_144745_040](https://github.com/user-attachments/assets/de498f6d-bcff-49c3-856a-828bc977e374)

**Comment by PaulElisha** [comment]
Submit your dorahack build link.

Cc: @zxstim

**Comment by samlovework** [comment]
Below is my dorahacks build link:

https://dorahacks.io/buidl/20650/

**Comment by zxstim** [comment]
approved for `1010 KAIA (meetup cost) + 200 KAIA (for you) + 40 KAIA (community airdrop, equally split among everyone) = 1250 KAIA`

**Comment by zxstim** [comment]
closing
