### ISSUE TITLE
Proposal: ProtectedPay- Secure Social Payments Infrastructure with Built-in Escrow

### ISSUE THREAD

**Issue by Spydiecy** [kaiachain/kaia-dapp-mono#259]
### Description
**ProtectedPay is a comprehensive payment infrastructure that enables secure peer-to-peer transactions, group payments, and savings mechanisms on the Kaia blockchain. The protocol introduces protected transfer mechanisms with built-in escrow, username-based payments, and collaborative financial tools.**

### Core Functionalities:

1. Protected Transfers
- Escrow-based secure transactions
- Claim/refund mechanisms
- Username-based payment system

2. Group Payment System
- Multi-participant payment coordination
- Automatic distribution mechanisms
- Payment status tracking

3. Savings Infrastructure
- Collaborative savings pots
- Contribution tracking
- Secure withdrawal mechanisms

4. User Management
- Username registration system
- Transaction history tracking
- User profile management

### Why Proposal?

1. Simplifies Secure Transactions
- Eliminates need for external escrow services
- Reduces risk in P2P transactions
- Makes crypto payments more accessible

2. Enhances User Experience
- Username-based payments instead of complex addresses
- Intuitive group payment coordination
- Clear transaction status tracking

3. Enables Financial Collaboration
- Group payment coordination
- Shared savings mechanisms
- Transaction transparency

### Bounty Track: :-

**DeFi Infrastructure-** 
The project provides essential DeFi primitives that enable secure and user-friendly financial transactions on Kaia. It serves as foundational infrastructure for future financial applications while solving immediate user needs for protected payments and group coordination.

**Comment by zxstim** [comment]
Can you reduce your scope? I need you to structure it like this:
I will build X that does Y (single feature).

You can open an `Update` issue after to add more features/improvements.

**Comment by Spydiecy** [comment]
> Can you reduce your scope? I need you to structure it like this: I will build X that does Y (single feature).
> 
> You can open an `Update` issue after to add more features/improvements.

Oh i cannot submit a project with all the above functionalities?
Like i have been working on for a while i have the product ready with the things i have mentioned above, i will need to open the update thing you are talking about to add the extra features? 
Also adding all the stuff would get me a better chance at the bounty right?

**Comment by zxstim** [comment]
Ah ok. Submit and i will check.

**Comment by Spydiecy** [comment]
BUIDL : https://dorahacks.io/buidl/20120
Github: https://github.com/Spydiecy/ProtectedPay_Kaia

**Comment by zxstim** [comment]
you should buy a domain name and run it as a project

**Comment by Spydiecy** [comment]
> you should buy a domain name and run it as a project

You like it? , if i get a good bounty, i ll be able to even be able do proper advertising about with plus and deploy it on the klaytn mainnet too. I m thinking of charging  very low txn fee to make it profitable on the refund system as if they make a wrong payment the funds are lost forever, this way they will regain all fo it with just a little fee, what do you say?

**Comment by Spydiecy** [comment]
The BUIDL hasnt been reviewed by the dorahacks team till now, here is the video demop plus the live site: https://youtu.be/kQctR6ypspI, https://protectedpay-kaia.netlify.app/

**Comment by Spydiecy** [comment]
dorahacks BUIDL is live, kindly have a look at it
BUIDL : https://dorahacks.io/buidl/20120
Github: https://github.com/Spydiecy/ProtectedPay_Kaia

Submitted.

**Comment by Spydiecy** [comment]
@zxstim did u take a look at it?

**Comment by zxstim** [comment]
Oops. Will check now. Pls ping every few days to remind me.

**Comment by Spydiecy** [comment]
> Oops. Will check now. Pls ping every few days to remind me.

Did you check now ? what was your review on it?

**Comment by Spydiecy** [comment]
@zxstim pls give me feedback, i want to take this project to the klaytn mainnet too, plus have been working on upgrading a lot of stuff so the sooner you could gimme feedback on the initial thing the quicker i could make this a really good project, Thanks, Regards Tanishq.

**Comment by Spydiecy** [comment]
@zxstim ?

**Comment by zxstim** [comment]
overall, i think it's ok. Can you upload the contract github as well?

**Comment by Spydiecy** [comment]
> overall, i think it's ok. Can you upload the contract github as well?

Sure

**Comment by kaia-dev-intern** [comment]
just FYI,

https://x.com/KaiaDevIntern/status/1866841240433725729

set up a community here for you:
https://x.com/i/communities/1867063240926302471

**Comment by Spydiecy** [comment]
> just FYI,
> 
> https://x.com/KaiaDevIntern/status/1866841240433725729
> 
> set up a community here for you: https://x.com/i/communities/1867063240926302471

Alright

**Comment by Spydiecy** [comment]
@kaia-dev-intern @zxstim  

Official Twitter/X account : https://x.com/ProtectedPay

Official Post: https://x.com/ProtectedPay/status/1867201402742947990

Kaia Community Post: https://x.com/Tanishqistaken/status/1867202927841956183

**Comment by zxstim** [comment]
@Spydiecy can you upload the contract github too for getting `cleared` tag?

**Comment by zxstim** [comment]
Approved for `1120 KAIA with 50% penalty = 560 KAIA`

**Comment by zxstim** [comment]
closing

**Comment by Spydiecy** [comment]
> @Spydiecy can you upload the contract github too for getting `cleared` tag?

![image](https://github.com/user-attachments/assets/447e3a37-3241-4a0c-a085-79588f2865fe)

**Comment by Spydiecy** [comment]
> Approved for `1120 KAIA with 50% penalty = 560 KAIA`

@zxstim 
I feel like the penalty shouldn't be applied though, as the project was submitted in the previous phase the odyssey one. Plus i m actively posting on X too. Would appreciate if you reconsider it. It will motivate me to upgrade this project actively. Thanks. Regards,
Tanishq

**Comment by Spydiecy** [comment]
> Approved for `1120 KAIA with 50% penalty = 560 KAIA`

Also where should i provide the address for the payment?

**Comment by zxstim** [comment]
How about this. There are some UI bugs (non working links, unresponsive actions/buttons, etc.)

Make a new Issue with the Update template, fix those bugs and submit again. I will add the 50% bonus into that submission.

**Comment by zxstim** [comment]
Right now Dorahacks is replenishing the pool so you have to wait anyway. Do it in a day or 2 and get 2 payouts

**Comment by zxstim** [comment]
@Spydiecy provide address here with a BUIDL. You have the BUIDL there already. Just update it with an address and send here your BUIDL link

https://dorahacks.io/hackathon/kaia-winter-epoch/detail#submission-guidelines

**Comment by zxstim** [comment]
and btw, you don't have to split repo to earn the grant here. I prefer you keep it in your main repo (it's ok to be multichain). Just make sure you have contract deployments on kaia and your frontend supports Kaia

i want the project to be the best for the user rather than tying you in

**Comment by zxstim** [comment]
next time, don't forget to ping me every 2 days or so. There are a lot of submissions so i forget all the time

**Comment by Spydiecy** [comment]
> How about this. There are some UI bugs (non working links, unresponsive actions/buttons, etc.)
> 
> Make a new Issue with the Update template, fix those bugs and submit again. I will add the 50% bonus into that submission.

sure i will update the stuff

**Comment by Spydiecy** [comment]
> Right now Dorahacks is replenishing the pool so you have to wait anyway. Do it in a day or 2 and get 2 payouts

oh cool, thx

**Comment by Spydiecy** [comment]
> @Spydiecy provide address here with a BUIDL. You have the BUIDL there already. Just update it with an address and send here your BUIDL link
> 
> https://dorahacks.io/hackathon/kaia-winter-epoch/detail#submission-guidelines

![image](https://github.com/user-attachments/assets/c77260c1-c76b-4127-805c-68bc4983b305)

https://dorahacks.io/buidl/20120

**Comment by Spydiecy** [comment]
> and btw, you don't have to split repo to earn the grant here. I prefer you keep it in your main repo (it's ok to be multichain). Just make sure you have contract deployments on kaia and your frontend supports Kaia
> 
> i want the project to be the best for the user rather than tying you in

Oh i see, cool will keep in mind . Will make the final version with all the chain abstraction multi chain stuff soon

**Comment by Spydiecy** [comment]
> next time, don't forget to ping me every 2 days or so. There are a lot of submissions so i forget all the time

Haha actually i saw someone doing the same and was marked as spam so didnt do it that time lol

**Comment by Spydiecy** [comment]
@zxstim Should i apply with the update template now?

**Comment by zxstim** [comment]
yea open new issue with Update template and reference this issue number

**Comment by Spydiecy** [comment]
Alright will do, thx

**Comment by Spydiecy** [comment]
@zxstim here u go : https://github.com/kaiachain/kaia-dapp-mono/issues/316
