### ISSUE TITLE
Update: Added dApps platform to GM GN Wallet

### ISSUE THREAD

**Issue by haxxstig** [kaiachain/kaia-dapp-mono#261]
Description
- Improved UX flow
- Added dApps platform (component to integrate external dapps)
- Added multisend dapp

Reference issue
- #196 

Category
- Other

**Comment by zxstim** [comment]
Approved to proceed

**Comment by haxxstig** [comment]
Updated on public dev branch here: https://dev.gmgn.app

Github: https://github.com/gmgn-app/gmgn

**Comment by zxstim** [comment]
Approved `2500 KAIA` bounty. Smooth work with the multisend.

**Comment by zxstim** [comment]
Closing for payout
