### ISSUE TITLE
Proposal: A dedicated kaiascan SDK in python

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#268]
Description

This proposal outlines the need for a dedicated KaiaScan SDK in Python, detailing its benefits and functionalities. KaiaScan, a blockchain explorer specifically designed for the Kaia ecosystem, provides real-time data tracking and insights into token movements, transactions, and more.

Core functionalities:
Token information retrieval
Transaction tracking
Block information
Contract Interaction

Why proposal?
It simplifies the integration of kaiascan functionalities into application.
It encapsulate api calls making it a user-friendly approach to access kaia blockchain information.
Enhanced developer experience

Bounty track

Developer tool

**Comment by zxstim** [comment]
You have spelling issue with "Go" instead of "python"

**Comment by PaulElisha** [comment]
Oh, I will fix that.

Re: It has been fixed.

**Comment by PaulElisha** [comment]
GitHub: https://github.com/PaulElisha/kaiascan-sdk-py
dorahack: https://dorahacks.io/buidl/20150

**Comment by zxstim** [comment]
approved for `1500 KAIA` payout

**Comment by zxstim** [comment]
closing
