### ISSUE TITLE
Proposal: Telegram Bot for klaytn or kaia (after launch)

### ISSUE THREAD

**Issue by anudeep11k** [kaiachain/kaia-dapp-mono#27]
Description
- A simple Telegram bot for comparing the klaytn into many fiat currencies , and also monitoring a klaytn address with NFTs and KIP tokens that a individual address is holding 

Bounty track
- Hacker Meet

**Comment by zxstim** [comment]
Cool. Revert back with your implementation.

**Comment by anudeep11k** [comment]
Repo Link : https://github.com/anudeep11k/TELEBOTKLAY
Bot link : https://t.me/klaypricebot
Commands are specific for specific actions

**Comment by zxstim** [comment]
Looks good. Works well. Approved for 100 KLAY bounty payout. Send me an email 0x.stim@klaytn.foundation to collect. Open a PR at [https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md](https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md) and follow the instruction to add your submission in.

**Comment by zxstim** [comment]
Closing this issue and mark as Done. If you want to keep building up on your previous submission, open a new issue and propose the new changes.
