### ISSUE TITLE
Proposal: Subgraph for DragonSwap

### ISSUE THREAD

**Issue by anudeep11k** [kaiachain/kaia-dapp-mono#273]
Description
- Github link [Repo](https://github.com/anudeep11k/dragon-subgraph)
- Created Subgraph for dgswap
- added subgraph link in readme of repository 
- here is the link for subgraph and its indexed, deployed, published. [Subgraph-dqswap](https://thegraph.com/studio/subgraph/subgraph-dgswap)
- for api endpoints, here you can check [link](https://thegraph.com/studio/subgraph/subgraph-dgswap/endpoints)

Bounty Track 
- Kaia fall odyssey
- My build link dorahacks https://dorahacks.io/buidl/20201

**Comment by zxstim** [comment]
<img width="1265" alt="image" src="https://github.com/user-attachments/assets/12418abe-2edf-49e8-b3b9-8231a2e6cd41">

**Comment by anudeep11k** [comment]
https://thegraph.com/studio/subgraph/subgraph-dgswap
but i can access here , wondering whats wrong

**Comment by zxstim** [comment]
approved for `950 KAIA`

**Comment by zxstim** [comment]
closing
