### ISSUE TITLE
Proposal: Experiment of a X contribution program

### ISSUE THREAD

**Issue by kaia-dev-intern** [kaiachain/kaia-dapp-mono#275]
Description
- Similar to this program from Berachain (https://x.com/0xoogabooga/status/1859330828267897309)
- Goal is to encourage interaction with Kaia ecosystem (projects and community)
- Foster conversation and incentivize the community directly rather going through agencies/KOLs
- Posts are rewarded based on originality, humor, usefulness, earnestness.
- Instead of using a different, the winner just DM KaiaDevIntern.

Bounty track
- Cultural Feast

**Comment by zxstim** [comment]
Approved for `2000 KAIA` to trial this

**Comment by zxstim** [comment]
Closing
