### ISSUE TITLE
Update: permit2 example integration

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#276]
Description
- This proposal is to convert the permit2 example integration repo into a full permit2-kit for kaia
- It's been updated to include a test utility file that will help developers to quickly test their permit2 integrated smart contract on kaia.
- It showcases how to use the test utility file.
- The test utility file contains utility to test permit2 transfer and permit2 batch transfer.
- It contains an helper function to make a batch transfer of tokens in a single transaction with a single approval.

Reference issue
- Link to previously submitted [#253 ]

Category
- Developer tool

**Comment by PaulElisha** [comment]
[GitHub](#271)
[DoraHack](https://dorahacks.io/buidl/20054)

**Comment by zxstim** [comment]
there is a recursion joke somewhere here with the github link loop ahaha

anyway, add the actual repo links rather than the issue link

**Comment by PaulElisha** [comment]
Lol.

This is it: https://github.com/PaulElisha/permit2-test-integration

**Comment by zxstim** [comment]
Approved for `850 KAIA`

**Comment by zxstim** [comment]
closing for payout
