### ISSUE TITLE
Kaia Connect: React Wormhole Frontend Toolkit

### ISSUE THREAD

**Issue by CoderOfPHCity** [kaiachain/kaia-dapp-mono#277]
Description
An Implementation set up of a React TypeScript application that integrates with the Wormhole SDK for cross-chain messaging on Kaia chain and other EVM based chains.

-supports native and wrapped token transfers directly into an application in as few as 3 lines of code.
-Connect transfers only require gas fees on the source chain. Relayers drop users off with native gas tokens on the destination chain for instant transactions.

Frontend: https://kaia-react-connect-wormhole-ntt-framwork-sdk.vercel.app/
GitHub:https://github.com/CoderOfPHCity/Kaia-React-Connect-Wormhole-NTT-Framwork-SDK

Dorahack: https://dorahacks.io/buidl/20440

Bounty track
- Developer tooling

**Comment by zxstim** [comment]
Approved and marked as submitted

**Comment by zxstim** [comment]
application is not very polished. but I will approve `300 KAIA` bounty for the effort

**Comment by zxstim** [comment]
closing
