### ISSUE TITLE
Article on A Step-by-Step Guide to Verifying Smart Contracts with Kaia Hardhat

### ISSUE THREAD

**Issue by CoderOfPHCity** [kaiachain/kaia-dapp-mono#282]
Description
Verifying smart contracts on Kaia using Hardhat can be daunting due to outdated and unclear instructions in the official documentation. This article provides an updated, concise guide to streamline the process for developers. 

Leveraging the latest Hardhat CLI and optimized settings, you'll learn how to configure your hardhat.config.js for Klaytn mainnet or testnet, use the Hardhat Verify Plugin, and execute seamless contract verification directly from your terminal. 

With this tutorial guide users can confidently submit their source code to Kaiascope for verification with ease in very few simplified steps.

Bounty track
- Developer tooling
- Education

**Comment by zxstim** [comment]
i think this one is well covered already. 

And we have issues with the actual explorer itself not supporting automated verification. Kaiascan is also preferable compared to kaiascope

**Comment by zxstim** [comment]
gonna mark this as invalid and close
