### ISSUE TITLE
Proposal: Developing a Tower Defense Telegram Game Integrated with KAIA Chain

### ISSUE THREAD

**Issue by KelvinTrinhSG** [kaiachain/kaia-dapp-mono#289]
Description:

- Tower Defense game on Telegram platform.
- Starts via a Telegram bot for easy access and gameplay.
- Integrated with blockchain technology for secure and transparent interactions.
- Players can use KAIA Testnet tokens to purchase in-game items.
- Offers a seamless and innovative gaming experience on the blockchain.

Bounty track
- Others

![Image1](https://github.com/user-attachments/assets/2a53eb31-b757-4e2d-80b3-9ffd8b8f2727)
![Image2](https://github.com/user-attachments/assets/30bcc3f1-5cac-456e-a5dc-5ec397bf0ed1)

**Comment by zxstim** [comment]
Approved. Please proceed

**Comment by KelvinTrinhSG** [comment]
@zxstim 
🎮 Excited to share! I've just launched Kaia Tower Defense on Telegram! 🚀 Dive into the action, defend your towers, and explore the power of Kaia. 💎 Come play and enjoy!

Telegram Bot: @KaiaTowerDefenseGamebot
Github: https://github.com/KelvinTrinhSG/Tower-Defense-Telegram-Game-on-KAIA
Youtube: https://www.youtube.com/watch?v=iDXCFc1kPGA
Twitter: https://x.com/CoinInves2024/status/1864303354215846024

**Comment by KelvinTrinhSG** [comment]
@zxstim
Kindly send to you the build link on DoraHacks. Thank you!

https://dorahacks.io/buidl/20472

**Comment by zxstim** [comment]
Approved for `2000 KAIA` bounty

**Comment by zxstim** [comment]
closing
