### ISSUE TITLE
Update: UI/UX overhaul for GM GN Wallet

### ISSUE THREAD

**Issue by haxxstig** [kaiachain/kaia-dapp-mono#295]
Description
- UI and UX improvements through out the wallet for all sections
- Improve payment experience
- Improve multisend
- Improve WalletConnect integration

Reference issue
- #261

Category
- Other

**Comment by zxstim** [comment]
Approved

**Comment by haxxstig** [comment]
Deployment: https://gmgn.app
Repo: https://github.com/gmgn-app/gmgn

**Comment by zxstim** [comment]
Approved for `1650 KAIA`

**Comment by zxstim** [comment]
closing

**Comment by haxxstig** [comment]
Dorahacks BUIDL: https://dorahacks.io/buidl/15990
