### ISSUE TITLE
Proposal: Sigpass library for Passkey based in-app wallet

### ISSUE THREAD

**Issue by internuwu** [kaiachain/kaia-dapp-mono#296]
Description
- in-app wallet can improve UX for the DApp a lot (own the user journey entirely)
- Wagmi + viem based (super popular frontend library)
- Passkey based so super simple and convenient
- Documentation included

Bounty track
- Developer tools

**Comment by zxstim** [comment]
Approved

**Comment by internuwu** [comment]
Repository: https://github.com/gmgn-app/sigpass
Dorahacks BUIDL: https://dorahacks.io/buidl/20695

**Comment by zxstim** [comment]
Approved for `1200 KAIA`. Closing
