### ISSUE TITLE
Update: Frontend for Multi-User Challenge Room

### ISSUE THREAD

**Issue by 0xLou1s** [kaiachain/kaia-dapp-mono#297]
Description
# Frontend for Multi-User Challenge Room

### **Real-Time Collaborative Environment**
- **Challenge Room Creation**:  
  - Users can join a shared challenge room to interact with each other and participate in the challenge.
  - Each room dynamically updates based on real-time user interactions.
  
- **Live Updates**:  
  - WebSocket integration ensures all users see updates immediately (e.g., new prompts, responses, or transaction statuses).
  
- **User Identity**:  
  - Each user’s wallet address serves as their unique identifier, displayed alongside their messages.

---

### **Secure Prompt Handling**
1. **Prompt Preparation**:  
   - Users input their challenge prompt through an intuitive UI.  
   - The system attaches the user's wallet address to the prompt.

2. **Generate pHash**:  
   - Locally hashes the prompt and wallet address using a secure hash function (e.g., SHA-256).  
   - Formula: `pHash = Hash(prompt + walletAddress)`.

3. **Smart Contract Submission**:  
   - Displays the transaction details (e.g., pHash and fee amount) for user review.
   - Prompts the user to sign the transaction using their connected wallet.  
   - Sends the transaction data to the smart contract for further processing.

---

### **Data Submission**
- Simultaneously with the smart contract call, the frontend sends the following data to the backend via an API:
  - The original **prompt**.
  - The user’s **wallet address**.
  - The generated **pHash**.

### **Feedback and Updates**
- Upon receiving the LLM's response from the backend, the frontend displays:
  - **LLM Text Response**: A detailed explanation of the action taken.
  - **Action Result**:
    - `RejectTransfer`: Feedback on why the attempt was rejected, along with any provided suggestions.
    - `ApproveTransfer`: Confirmation of success, including the transaction ID and leaderboard update.

Reference issue
- #287

Category
- Defi

**Comment by 0xLou1s** [comment]
source code : https://github.com/Lou1sVuong/athena-ai

**Comment by zxstim** [comment]
Ok checking

**Comment by zxstim** [comment]
Approved for `1500 KAIA` bounty

**Comment by zxstim** [comment]
closing

**Comment by 0xLou1s** [comment]
I have updated the buidl link on DoraHacks. Thank you!

Buidl on Dorahack : https://dorahacks.io/buidl/20628
