### ISSUE TITLE
Proposal: Fruit Frenzy: A Super Cute Puzzle Game on Kaia | Telegram Game Edition 🎮🍓

### ISSUE THREAD

**Issue by langsky302** [kaiachain/kaia-dapp-mono#299]
**Description:**
- Telegram-integrated Match-3 Puzzle Game
- Built on the KAIA blockchain for seamless transactions
- Features adorable and vibrant graphics
- Offers engaging and addictive gameplay
- Perfect for puzzle lovers seeking a blockchain-powered experience 🍓🎮✨

Bounty track
- Others

Since I was so excited about the Telegram Game Development Guideline by KelvinCOD that I went ahead and completed the product already!

Telegram Bot: @FruitFrenzyGameKAIAbot
Github: https://github.com/langsky302/Fruit-Frenzy-Game-On-Kaia
Youtube: https://www.youtube.com/watch?v=QkvlnJLnMpc
Twitter: https://x.com/SkyLang357794/status/1865027463086248255

**Comment by zxstim** [comment]
hmm wallet connection is gonna be really bad

prob need an in-mini-dapp wallet. but just make the game first to claim first bounty and you can improve the wallet UX for user

**Comment by langsky302** [comment]
@zxstim 
Yes, your comment is absolutely correct, anh Vic.
I also plan to improve the UX for Connect Wallet right away.
Currently, the game is complete and can already be played on the Telegram App.
If possible, please help me finalize phase 1 to have a bit of funding as motivation.
I will enhance the UX for Connect Wallet immediately.
Thank you so much for your support.

![image](https://github.com/user-attachments/assets/4c2f1ee5-eb43-4c33-adae-54d1a5d625e0)
![image](https://github.com/user-attachments/assets/28a4c6f0-7417-4d6e-ace3-f2e179e1537a)
![image](https://github.com/user-attachments/assets/b4acbcca-ec1c-4712-932c-2eb6c23dcb35)

**Comment by zxstim** [comment]
a bit smaller game so `1200 KAIA`

**Comment by zxstim** [comment]
closing
