### ISSUE TITLE
Update: An update to KaiaScan SDK rs

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#300]
Description
- It's an SDK that helps developers easily integrate with the Kaia blockchain.
- 
Reference issue
- #250 
Category
- Developer tool

**Comment by PaulElisha** [comment]
Github repo: https://github.com/PaulElisha/kaiascan-sdk-rs

dorahack: https://dorahacks.io/buidl/20040

**Comment by zxstim** [comment]
approved for `850 KAIA` bounty

**Comment by zxstim** [comment]
closing
