### ISSUE TITLE
Update: An update to KaiaScan SDK ts

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#301]
Description
- It's an SDK that helps developers easily integrate with the Kaia blockchain.

Reference issue
- #238 
Category
- developer tool

**Comment by PaulElisha** [comment]
GitHub repo: https://github.com/PaulElisha/kaiascan-sdk-ts

dorahack: https://dorahacks.io/buidl/19222

**Comment by zxstim** [comment]
Approved for `850 KAIA` bounty

**Comment by zxstim** [comment]
closing
