### ISSUE TITLE
Update: An update to KaiaScan SDK Go 

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#302]
Description
- It's an SDK that helps developers easily integrate with the Kaia blockchain.

Reference issue
- #237

Category
- developer tool

**Comment by PaulElisha** [comment]
GitHub repo: https://github.com/PaulElisha/kaiascan-sdk-go

dorahack: https://dorahacks.io/buidl/19153

**Comment by zxstim** [comment]
Approved for `850 KAIA`

**Comment by zxstim** [comment]
closing
