### ISSUE TITLE
Proposal: Developing Desert Hunter Game with KAIA, stunning UI, and gameplay to enrich the player experience like never before

### ISSUE THREAD

**Issue by trandrewsg91** [kaiachain/kaia-dapp-mono#305]
**Description:**

- **Breathtaking graphics:** Stunning, meticulously detailed visuals that captivate players.
- Polished design: Every element crafted for a seamless and immersive experience.
- KAIA integration: Enriching gameplay with advanced blockchain technology.
- Engaging gameplay: Action-packed desert adventures to keep you hooked.
- Innovative development: Leveraging cutting-edge tools for an exceptional game.
- Smooth UI: Intuitive and sleek interface for effortless navigation.

**Bounty track**
- Other

Video: https://www.youtube.com/watch?v=5PGLLgTiLxw
Play Game: https://trandrewsg91.itch.io/kaia-desert-hunter-game
Git: https://github.com/trandrewsg91/Desert-Hunter-Game-On-Kaia
Twitter: https://x.com/TranDrew251678/status/1866103552424497364

![image](https://github.com/user-attachments/assets/fd48e62a-c9cd-40c9-afad-7f6607cec5d7)
![image](https://github.com/user-attachments/assets/4282d465-215f-4c33-927e-87d67df938bb)
![image](https://github.com/user-attachments/assets/052fda13-f036-4658-8616-493b211f20fa)
![image](https://github.com/user-attachments/assets/3eccbfe0-0792-4593-8bd2-81aec1736d37)

**Comment by trandrewsg91** [comment]
Dear anh @zxstim 

I have completed submitting to Dorahack as below link:

https://dorahacks.io/buidl/20692

Thank you very much for your wonderful support.

**Comment by zxstim** [comment]
Approved for `1120 KAIA with a 50% penalty = 560 KAIA`

Note: https://x.com/KaiaDevIntern/status/1866841240433725729

**Comment by zxstim** [comment]
closing
