### ISSUE TITLE
Proposal: Wefit365

### ISSUE THREAD

**Issue by nhatlapross** [kaiachain/kaia-dapp-mono#307]
Description
- WeFit365 envisions a world where fitness is not just a personal pursuit but a rewarding lifestyle. Our mission is to empower individuals to achieve their health goals while earning cryptocurrency as a tangible incentive. We aim to create a vibrant community of fitness enthusiasts who are motivated to stay active, improve their well-being, and benefit financially from their dedication. By leveraging technology and blockchain, we strive to revolutionize the fitness industry, making it more accessible, engaging, and rewarding for all.

Bounty track
- Education
- NFT

**Comment by nhatlapross** [comment]
![image](https://github.com/user-attachments/assets/141a3f2b-ea61-4080-a64e-56b1bb635bda)
Mint NFT and start your Fitness journey
![image](https://github.com/user-attachments/assets/e890f044-d5ed-42ee-a530-29c780e2ca20)
By completing daily tasks, you can earn points and level up your NFTs.
![image](https://github.com/user-attachments/assets/f30ca1ef-d2cd-4319-90c2-88404436b27a)
Experience personalized training with an AI coach that provides real-time form correction.
![image](https://github.com/user-attachments/assets/2e9fde60-700f-4f61-80ae-5fadb2e25ce3)
Stay motivated and engaged with our community contests, offering a chance to win amazing prizes.
![image](https://github.com/user-attachments/assets/c8f1145f-c2e7-440c-8ec8-579e1038ed52)
Manage your blockchain assets
![image](https://github.com/user-attachments/assets/b0d6ba70-b967-4069-8b22-c18874b269e1)
Trade your NFTs for other digital assets on the marketplace.
![image](https://github.com/user-attachments/assets/81d829a6-8f55-4df7-99c2-c9a407576569)

**Comment by zxstim** [comment]
interesting. approved

**Comment by nhatlapross** [comment]
phase 1: 
[demo video phase 1](https://www.youtube.com/watch?v=uYI52M_M9F8)
[demo mvp feature](https://wefit365.onrender.com/)

**Comment by zxstim** [comment]
can you upload your source code as well?

**Comment by nhatlapross** [comment]
Public source code at: https://github.com/nhatlapross/Wefit-AI-Trainer

**Comment by zxstim** [comment]
Cool. Approved for `1675 KAIA with 50% penalty = 837.5 KAIA` (reason is here https://x.com/KaiaDevIntern/status/1866841240433725729)

keep building and get active on X to claim the 50% bonus in the next submission

**Comment by zxstim** [comment]
closing

**Comment by zxstim** [comment]
please also make a dorahacks BUIDL and send it here

**Comment by nhatlapross** [comment]
> please also make a dorahacks BUIDL and send it here
dorahacks BUILDL at: https://dorahacks.io/buidl/14831
