### ISSUE TITLE
Proposal: Developing Kaia Zombie Hunter Game to redefine gaming on Kaia Chain

### ISSUE THREAD

**Issue by KelvinTrinhSG** [kaiachain/kaia-dapp-mono#308]
**Description**

- Title: Kaia Zombie Hunter Game
- Type: Blockchain-integrated action game
- Blockchain: Kaia Chain
- Currency: $KLAY for in-game purchases
- Wallet Support: MetaMask integration
- Core Features: Zombie hunting, skill upgrades, NFT utilization
- Purpose: Deliver an immersive gaming experience on Kaia Chain

**Bounty track**
- NFT, GameFi, Other

Play Game: https://thkien85.itch.io/zombie-hunter-game-on-kaia
Video: https://www.youtube.com/watch?v=noS_6m0w2xA
Github: https://github.com/KelvinTrinhSG/Zombie-Hunter-Game-On-Kaia-Chain

Images:

![image](https://github.com/user-attachments/assets/33a5b150-6278-40ec-9c46-fda632a2223e)
![image](https://github.com/user-attachments/assets/31b80a2e-1402-4e85-970d-4fcbb6deb856)
![image](https://github.com/user-attachments/assets/f9952e07-4c83-4005-83c2-40ea860729ed)
![image](https://github.com/user-attachments/assets/47291fde-4eac-4bbd-a9dd-c9c053585b4f)
![image](https://github.com/user-attachments/assets/63575863-13b4-4b31-b750-10b136753d1f)

**Comment by KelvinTrinhSG** [comment]
Dear @zxstim 
I have submitted my build on the DoraHacks website.
Below is the link to my build.
Thanks and have a nice day.

https://dorahacks.io/buidl/20676

**Comment by zxstim** [comment]
Approved for `1120 KAIA with a 50% penalty = 560 KAIA`

Note: https://x.com/KaiaDevIntern/status/1866841240433725729

**Comment by zxstim** [comment]
closing
