### ISSUE TITLE
Update: An update to the dedicated Kaiascan sdk py

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#310]
Description
- It's an SDK that helps developers easily integrate with the Kaia blockchain.

Reference issue
- #268 

Category
- developer tool

**Comment by PaulElisha** [comment]
Github: https://github.com/PaulElisha/kaiascan-sdk-py
dorahack: https://dorahacks.io/buidl/20150

**Comment by zxstim** [comment]
aight checking

**Comment by zxstim** [comment]
Approved for `1000 KAIA`

**Comment by zxstim** [comment]
closing
