### ISSUE TITLE
Update: ProtectedPay

### ISSUE THREAD

**Issue by Spydiecy** [kaiachain/kaia-dapp-mono#316]
Description
- non working links fixed 
- unresponsive actions/buttons fixed
- all ui bugs fixed

Reference issue
- #259 

Category
- Defi, Infrastructure

**Comment by Spydiecy** [comment]
DoraHacks Buidl : https://dorahacks.io/buidl/20120
Github : https://github.com/Spydiecy/ProtectedPay_Kaia

@zxstim fixed the stuff you asked

**Comment by Spydiecy** [comment]
@zxstim just giving the reminder for you to review the stuff, thx

**Comment by Spydiecy** [comment]
@zxstim hello?

**Comment by zxstim** [comment]
just tagging my handle is ok

some UI crunch with addresses taking up a lot of space. but overall it's ok. Small update tho so approved for

`300 KAIA + 50% bonus 560 KAIA = 860 KAIA`

**Comment by zxstim** [comment]
closing

**Comment by Spydiecy** [comment]
> just tagging my handle is ok
> 
> some UI crunch with addresses taking up a lot of space. but overall it's ok. Small update tho so approved for
> 
> `300 KAIA + 50% bonus 560 KAIA = 860 KAIA`

Some queries in this breakdown so the new amount is 300 and previous amount 560? or the 560 from the last one is seperate? @zxstim

**Comment by zxstim** [comment]
it's the 560 KAIA penalty from last submission

the 300 KAIA is for this submission. Smaller updates so smaller payout

**Comment by zxstim** [comment]
Next, i suggest put the savings pot into something like rhombus (https://docs.rhombusprotocol.io/) for real yield

**Comment by Spydiecy** [comment]
> it's the 560 KAIA penalty from last submission
> 
> the 300 KAIA is for this submission. Smaller updates so smaller payout

Ah i see, thanks!
