### ISSUE TITLE
Update: Athena AI Chat - Frontend & Backend, LLM Integration.

### ISSUE THREAD

**Issue by 0xLou1s** [kaiachain/kaia-dapp-mono#322]
Description

1. **Core Chat Interface**:
- Implemented responsive chat layout with message bubbles
- Added user address display with HoverCard hover functionality
- Integrated AI/User avatars with Robohash generation
- Added typing animation for AI responses using TypingAnimation component
- Added highlight (🏆) for winning messages
- Added top loader for API request feedback

2. **Wallet & Blockchain Integration**:
- Implemented ConnectWalletBtn with Shimmer effect
- Added wallet connection state management
- Integrated prize pool display with NumberTicker animation
- Smart contract interaction for buy-in (0.01 ETH per attempt)
- Transaction state handling (pending/loading/success)
- Real-time balance updates using wagmi hooks

3. **Sidebar & Information Display**:
- Responsive sidebar with prize pool, about, rules sections
- Live prize pool updates using blockchain data
- Dynamic token symbol and decimal handling
- Proper formatting for cryptocurrency values

4. **State & Data Management**:
- Message synchronization with MongoDB
- Win state persistence and detection
- User session handling with wallet connection
- Real-time prize pool updates
- Message history retrieval and display

5. **API & LLM Integration**:
- POST/GET endpoints for message handling
- LLM response processing with decision making
- Message persistence in MongoDB
- Error handling and loading states
- Proper typing animation during AI response

6. **UI Components & Styling**:
- Custom Button component with loading states
- Responsive Card layouts
- Custom ScrollArea for chat history
- Toast notifications for actions
- AddressCardHover for wallet display
- Input component with proper states

7. **Security & Error Handling**:
- Message hashing before blockchain submission
- Proper error boundaries and fallbacks
- Loading states and user feedback
- Input validation and sanitization

8. **Environment & Configuration**:
- Smart contract addresses
- API endpoints
- Database configuration
- Wallet provider setup
- Network configurations

9. **Animations & User Feedback**:
- Typing animation for AI responses
- Loading spinners for transactions
- Smooth scroll behavior
- Hover effects and transitions
- Toast notifications

10. **Optimization & Performance**:
- Efficient database queries
- Proper component mounting/unmounting
- Optimistic UI updates
- Responsive design across devices
- Proper error handling

The system creates a seamless experience where users can:
- Connect their wallet
- View current prize pool
- Send messages with ETH buy-in
- Receive AI responses
- Track their win status
- Copy wallet addresses
- View transaction status
- See chat history

All components work together to provide a smooth, interactive experience while handling complex blockchain transactions, AI responses, and data persistence.

Reference issue
 - #297
 
Category

- Rise of the machines

**Comment by 0xLou1s** [comment]
I have updated the buidl and source code links . Thank you!

Source code : https://github.com/Lou1sVuong/athena-ai
Buidl on Dorahack : https://dorahacks.io/buidl/20628

**Comment by zxstim** [comment]
Approved for `1900 KAIA with 50% penalty = 950 KAIA`

get active on X to claim the 50% penalty

**Comment by zxstim** [comment]
closing
