### ISSUE TITLE
Proposal: AuditFi

### ISSUE THREAD

**Issue by Spydiecy** [kaiachain/kaia-dapp-mono#326]
Description

![image](https://github.com/user-attachments/assets/10595b0d-d42d-4adb-811f-b73dab72f78f)

Next-generation smart contract security powered by AI, delivering instant, on-chain audit reports across multiple networks.

Features:- 

1. AI-Powered Analysis  

2. Multi-Chain Support  
    Currently supporting:
    - Linea Sepolia Testnet
    - Neo X Testnet
    - Kaia Testnet

3. On-Chain Verification
  All audit reports are permanently stored on the blockchain.

4. Real-time Analysis
  Get instant security assessments of your smart contracts.

5. Interactive Dashboard
  Beautiful UI for viewing and managing audit reports.

6. Cross-Chain Reports
  View and compare audits across different networks.

- Live Demo : https://auditfi.vercel.app/
- Github : https://github.com/Spydiecy/AuditFi
- DoraHacks BUIDL : https://dorahacks.io/buidl/20904
- X/Twitter Account : https://x.com/AuditFi_ai
- X/Twitter Post : https://x.com/AuditFi_ai/status/1869619367614570650

Bounty track
- ROTM
- Developer Tools

**Comment by Spydiecy** [comment]
@zxstim

**Comment by Spydiecy** [comment]
https://x.com/AuditFi_ai/status/1870838630690041931

**Comment by Spydiecy** [comment]
> Description
> 
> ![image](https://private-user-images.githubusercontent.com/100078125/397243402-10595b0d-d42d-4adb-811f-b73dab72f78f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NDY0MzEsIm5iZiI6MTczNDk0NjEzMSwicGF0aCI6Ii8xMDAwNzgxMjUvMzk3MjQzNDAyLTEwNTk1YjBkLWQ0MmQtNGFkYi04MTFmLWI3M2RhYjcyZjc4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QwOTI4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODdkZGU4NTI3ZmExZmIwMmEwMTkwNGMzZWI0ODE4ZWQyZGQ1MDY0NTM1YzExNTYxNmUyYzMzYjk1MzNhZTdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H7ru1alDDm8dwh0M7KxoP8xR7xCEnzV-0Dch1D6akpo)
> 
> Next-generation smart contract security powered by AI, delivering instant, on-chain audit reports across multiple networks.
> 
> Features:-
> 
> 1. AI-Powered Analysis
> 2. Multi-Chain Support
>    Currently supporting:
>    
>    * Linea Sepolia Testnet
>    * Neo X Testnet
>    * Kaia Testnet
> 3. On-Chain Verification
>    All audit reports are permanently stored on the blockchain.
> 4. Real-time Analysis
>    Get instant security assessments of your smart contracts.
> 5. Interactive Dashboard
>    Beautiful UI for viewing and managing audit reports.
> 6. Cross-Chain Reports
>    View and compare audits across different networks.
> 
> * Live Demo : https://auditfi.vercel.app/
> * Github : https://github.com/Spydiecy/AuditFi
> * DoraHacks BUIDL : https://dorahacks.io/buidl/20904
> * X/Twitter Account : https://x.com/AuditFi_ai
> * X/Twitter Post : https://x.com/AuditFi_ai/status/1869619367614570650
> 
> Bounty track
> 
> * ROTM
> * Developer Tools

hello @zxstim pls provide any update, is this accepted or not, have submitted everything about the project here also here's the latest x post for this project ; https://x.com/AuditFi_ai/status/1871132256833884264

**Comment by zxstim** [comment]
Yea i spent a few days to think more about this (and what ideas should i deem invalid). so invalid just means it is not eligible for grants, not because it's bad.

So my rationale for this is:
- I think this is part of the bigger AI vertical (code review/generation) rather than crypto vertical.
- there is the `Rise of the Machine` category but it's for people building AI agent use cases for the crypto space. There are overlaps but think about the current AI agent meta on X.

So closing this and will mark it as `invalid`

**Comment by Spydiecy** [comment]
> Yea i spent a few days to think more about this (and what ideas should i deem invalid). so invalid just means it is not eligible for grants, not because it's bad.
> 
> So my rationale for this is:
> 
> * I think this is part of the bigger AI vertical (code review/generation) rather than crypto vertical.
> * there is the `Rise of the Machine` category but it's for people building AI agent use cases for the crypto space. There are overlaps but think about the current AI agent meta on X.
> 
> So closing this and will mark it as `invalid`

i feel like it could still fit some categor? no, people have been liking it so far, plus i m adding other cool thing aswell right now it uses gemini model but i m working on another decentralized model as well like on gaia. Plus adding other features of smart contract building etc

**Comment by Spydiecy** [comment]
Would appreciate if you would reconsider it as invalid @zxstim

**Comment by Spydiecy** [comment]
i mean overall its for people building on the kaia chain and want to get a soft audit of their contract, the improvements they should do etc stuff, plus it all stored on chain making the use of openness of the web3 space

**Comment by Spydiecy** [comment]
@zxstim ?
