### ISSUE TITLE
Proposal: an onchain membership experience

### ISSUE THREAD

**Issue by bsintern-uwu** [kaiachain/kaia-dapp-mono#37]
Description
- We want to craft a membership experience for our members entirely onchain
- Members get rewarded with NFTs based on contributions to our open source repositories, or attending our activities
- The membership is a NFT with a corresponding ERC6551 tokenbound account deployed on Kaia
- The ERC6551 tokenbound account allows accumulation of achievements, stats builds and more interactive experiences

Bounty track
- NFT

**Comment by zxstim** [comment]
Great use of ERC6551. Approve to proceed with the implementation.

**Comment by bsintern-uwu** [comment]
please find the complete implementation here: https://hq.buildstation.org/biochip

repositories:
dahsboard: https://github.com/buildstationorg/hq-dashboard
biochip contracts: https://github.com/buildstationorg/biochip-contracts

**Comment by zxstim** [comment]
Approved for payout of `1500 KLAY`

**Comment by zxstim** [comment]
Payout is completed so closing this issue. Open new issue if you submit an update.
