### ISSUE TITLE
Proposal: Kaia Foundry Template update

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#39]
Description
- A Foundry boilerplate to deploy smart contracts on Kaia with more integration with ecosystem projects and updated docs
- Hopefully I can get CREATE3 integrated as well

Bounty track
- Developer tooling

This issue is an update of: #18

**Comment by zxstim** [comment]
Alright. Approve to proceed.

**Comment by haxxsniper** [comment]
Reverting back with the update:
- Major revamp for docs and comments. Now every piece of code has comments. Added docs.
- Added CREATE3 deployment guide
- Added test cases and Kaia tokens

https://github.com/blockcmd/kaia-foundry-template

**Comment by zxstim** [comment]
Approved for `1500 KLAY` payout. Clean up a few typos, add a few more test cases and useful `make` commands for me.

**Comment by zxstim** [comment]
Closing this issue. Open new issue if you want to add an update.
