### ISSUE TITLE
Proposal: A website for the SoulBoundNFT community on Kaia (minters, airdrops and more great stuff)

### ISSUE THREAD

**Issue by SaitamaCoderVN** [kaiachain/kaia-dapp-mono#4]
# Description
I am embarking on a journey to create a groundbreaking decentralized application (dapp) that enables users to mint SoulBound Non-Fungible Tokens (NFTs) on the Kaia blockchain network. The concept of SoulBoundNFTs goes beyond mere digital ownership; it encapsulates the emotional connection and uniqueness of digital assets, fostering a deep bond between creators and collectors.

The SoulBoundNFT minter dapp will leverage the robust infrastructure of the Kaia blockchain, renowned for its scalability, security, and developer-friendly environment. Through this dapp, users will have the power to immortalize their digital creations, whether it be artwork, music, or any other form of digital content, as SoulBoundNFTs, imbued with a sense of authenticity and exclusivity.

By integrating with Klaytn, a leading blockchain platform with a strong community and ecosystem support, the SoulBoundNFT minter dapp aims to democratize the creation and ownership of NFTs, offering creators and collectors a seamless and efficient way to participate in the burgeoning digital asset space.

Furthermore, the development process will be open and transparent, as the source code will be hosted on the official GitHub repository of Klaytn. This not only ensures accountability but also invites collaboration and feedback from the wider developer community, fostering innovation and continuous improvement.

In summary, the SoulBoundNFT minter dapp on Klaytn represents a pioneering endeavor to redefine digital ownership and empower creators and collectors alike. With its user-centric design, seamless integration with Klaytn, and commitment to transparency, this dapp promises to revolutionize the way we perceive and interact with digital assets in the blockchain era.
# Bounty track
Contribute a free to use DApp onto mainnet

**Comment by FucktheKingcode** [comment]
Update proposal: I will add the user authentication functionality already in my discord and telegram communities to allow NFT minting and improve the UI/UX of the website.

**Comment by zxstim** [comment]
edit title to Kaia instead of Klaytn :D

**Comment by FucktheKingcode** [comment]
Yeah! Updated

**Comment by zxstim** [comment]
you haven't completed this bounty yet

**Comment by SaitamaCoderVN** [comment]
Oh so sorry, I thought I had already submitted it, I was so absent-minded.
It my website: https://soul-bound-community-kaia.vercel.app
My contract on Kaia: 0xFa593B4783e788B0F10cAc661b6dbc15E2165EF8
My contract on Kairos: 0xe6a6c69AEf46c72bF437dD7d90cDF6bEa9823d94

My repo front end: https://github.com/SaitamaCoderVN/Dragon_SoulBound_NFT.git
My repo contract: https://github.com/SaitamaCoderVN/Contract_SoulBoundNFT_Community.git

**Comment by zxstim** [comment]
Closing for completion
