### ISSUE TITLE
Proposal: Update on super efficient airdrop tool for Kaia

### ISSUE THREAD

**Issue by haxxsniper** [kaiachain/kaia-dapp-mono#43]
Description
- Integrate Kaia ecosystem projects into the airdrop tool. So ecosystem projects can airdrop to their community super easy.
- Improved UI further, more optimized

Bounty track
- Other

Related bounty submission: #1

**Comment by zxstim** [comment]
Approved to proceed. Revert back with implementation.

**Comment by haxxsniper** [comment]
Please find the implementation here:
https://blockcmd.com/drop

**Comment by zxstim** [comment]
Approved for `1500 KLAY` payout. Good work.

**Comment by zxstim** [comment]
Closing this issue for payout.
