### ISSUE TITLE
Proposal: Instructions for Interacting with Kaia Using Rust with Alloy Library

### ISSUE THREAD

**Issue by SaitamaCoderVN** [kaiachain/kaia-dapp-mono#45]
Description
- We need comprehensive instructions and examples for interacting with the Kaia blockchain using the Rust programming language and the Alloy library. This documentation should include the setup process, necessary dependencies, and code examples for common tasks such as sending transactions, querying smart contracts, and handling events. The goal is to provide a clear and detailed guide for developers looking to integrate Kaia functionalities into their Rust applications using Alloy.

1. Example Code:
- Include code examples for sending transactions to the Kaia blockchain.
- Provide examples of querying smart contracts.
- Show how to handle blockchain events.

2. Documentation:
- Ensure the documentation is clear, concise, and easy to follow.
- Include comments and explanations within the code examples.
- Provide links to any relevant external resources or documentation.

Bounty track
- Track: Education

**Comment by zxstim** [comment]
I like Rust. Approved.

**Comment by FucktheKingcode** [comment]
Yeah, thank you. 😍
My PR: https://github.com/kaiachain/kaia-dapp-mono/pull/44

**Comment by zxstim** [comment]
Approved for `200 KLAY` payout
