### ISSUE TITLE
Proposal: Comprehensive guide on ERC4626 Vault Contract, detailing general conception, vault math and security considerations.

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#51]
Description
- A comprehensive article that explains the vault contract, helps to understand the contract, the math, and some security considerations. 

Bounty track
-

**Comment by zxstim** [comment]
Approved for `700 KLAY` bounty

**Comment by zxstim** [comment]
Closing this issue because bounty has been paid. Open new one if you want to add updates.
