### ISSUE TITLE
Proposal: Update to the Kaia Foundry Pyth Template

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#53]
Description
- This is an update to the pyth price oracle price conversion library

Bounty track
- Developer tool

**Comment by zxstim** [comment]
Please attach the link to the repo here.

**Comment by PaulElisha** [comment]
> Please attach the link to the repo here.

https://github.com/PaulElisha/kaiachain-foundryTemplate--pricefeedManager-Price-converter

**Comment by zxstim** [comment]
Closing this issue because bounty has been paid. Open new one if you want to add updates.
