### ISSUE TITLE
Proposal: Price Feed Address Manager Contract

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#54]
Description
- This is a proposal to create price feed address manager contract that can quickly and easily help devs to fetch the price feed address of token pairs approved on Orakl to simplify development process and reduce the hurdle for scrambling docs.

Bounty track
- Developer tool

**Comment by zxstim** [comment]
Please attach the link to the repo here.

**Comment by PaulElisha** [comment]
> Please attach the link to the repo here.

https://github.com/PaulElisha/kaiachain-foundryTemplate--pricefeedManager-Price-converter

**Comment by zxstim** [comment]
Approved for `500 KLAY` payout for the `priceFeedManager` contract.
