### ISSUE TITLE
Proposal: Oklink sdk for kaiachain in Typescript

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#58]
Description
- This proposal is to create an oklink backend sdk for the kaiachian

Bounty track
- Developer tool

**Comment by zxstim** [comment]
Cool. We had a previous submission #15 here.

As per the rule, what would be your upgrades?

**Comment by PaulElisha** [comment]
> Cool. We had a previous submission #15 here.
> 
> As per the rule, what would be your upgrades/differentiation?

Handled proper error, modularise code and increased type enhancements,

**Comment by zxstim** [comment]
Cool. Approved to proceed. Revert back with repo link.

**Comment by PaulElisha** [comment]
> Cool. Approved to proceed. Revert back with repo link.

https://github.com/PaulElisha/oklink-kaiachain-ts

**Comment by zxstim** [comment]
Decent improvement. Approve for a `500 KLAY` bounty payout.

**Comment by zxstim** [comment]
Closing this issue because bounty has been paid. Open new one if you want to add updates.
