### ISSUE TITLE
Proposal: Oklink-sdk-python

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#60]
Description
- An OkLink sdk for the kaia chain written fully in python.

Bounty track

**Comment by PaulElisha** [comment]
https://github.com/PaulElisha/oklink-sdk-kaiachain-py

**Comment by zxstim** [comment]
Approved for `1300 KLAY` payout for this implementation. I would like one more additional version which is only a couple files (no boilerplate) for copy and paste into the codebase.

**Comment by zxstim** [comment]
Closing this issue because bounty has been paid. Open new one if you want to add updates.
