### ISSUE TITLE
Proposal: Kaia Safe Lite - Decentralized MultiSig wallet

### ISSUE THREAD

**Issue by JGatsby-29** [kaiachain/kaia-dapp-mono#65]
Description
- Kaia Mainnet-based decentralized multisig wallet
- It only consists of contract, so if another Kaia service requires a multi-sig wallet, they can get it right away.
- It can also be used for the educational purpose that even those who experience the multi-sig wallet for the first time can understand.

Bounty track
- Contribute a free to use DApp onto mainnet

**Comment by zxstim** [comment]
Sounds good ser. Please revert with the repos, links, etc.

Don't forget to create a BUIDL on dorahacks (https://dorahacks.io/hackathon/kaia-onchain-summer) as well

**Comment by zxstim** [comment]
I think your input here is `readonly`

![image](https://github.com/user-attachments/assets/aa15b3dc-acf7-410b-8c62-706227943438)

Can you fix this?

Please also copy and paste all your repo links and implementation link as well here. It's so the links show up often, helping people to see you more.

Anyway, approved for `1500 KLAY` bounty payout.

**Comment by JGatsby-29** [comment]
Can you fix this? 
-> okay, thank you for letting me know, I fixed that part,

Please also copy and paste all your repo links and implementation link as well here. 
-> [contract repo](https://github.com/JGatsby-29/safe-smart-contract-lite) / [front repo](https://github.com/JGatsby-29/safe-lite-wallet-web)

Thanks, I will continue to make many good products on Kaia Mainnet.

**Comment by zxstim** [comment]
You also need to create a BUIDL and submit here

https://dorahacks.io/hackathon/kaia-onchain-summer

**Comment by JGatsby-29** [comment]
Yes, I created the submission as you said, but it's under review now...!! 😭
![image](https://github.com/user-attachments/assets/fe14c56d-9cd4-44b1-b7ac-30048cd9a024)

**Comment by JGatsby-29** [comment]
Okay, I create and submit the BUIDL on Kaia Onchain Summer!
![image](https://github.com/user-attachments/assets/01faf7b5-f4d4-4e74-81dc-e79ee7f725ca)

**Comment by JGatsby-29** [comment]
oh thank you, I added that section.

```
----
Acknowledgement: I confirm the below address is my bounty payout address.
Payout address: 0x8a205CDC3B695568ccfBc2931c9dc1F5E8ab4728
```

**Comment by zxstim** [comment]
Closing this issue because bounty has been paid. Open new one if you want to add updates.
