### ISSUE TITLE
Proposal: Kaia's Transaction Lifecycle and Execution

### ISSUE THREAD

**Issue by jorshimayor** [kaiachain/kaia-dapp-mono#68]
Description
- This is an overview of the transaction lifecycle on Kaia, from creation and broadcasting to inclusion in a block and execution, including details on transaction types, fees, and error handling.

Bounty track
- Education

**Comment by zxstim** [comment]
Looks good. Imma set expectation here:
- Intro
- Details oriented, not too much jargon, focus on clear and concise points (doesn't have to be simple but no word salad)
- Graphs and diagrams to support your points
- Code if necessary to prove your point
- Bonus if you touch on some toolings like [kaia-sdk](https://github.com/kaiachain/kaia-sdk)

**Comment by jorshimayor** [comment]
Alright, looks good. I'll get started on it then. Thanks

**Comment by jorshimayor** [comment]
Hello, 

I'm done with this article and I'd like to get your opinion. Here's the google docs link:

https://docs.google.com/document/d/1MmvbgYV5gaLDnxuJY4Vc7WX2d4LDOx1Vd26vsLves2k/edit?usp=sharing

Thanks.

**Comment by zxstim** [comment]
Can you open a PR here and add your article in as a `.md` file?

https://github.com/kaiachain/kaia-dapp-mono/tree/main/learn

make the file name as `your-title-with-dashes.md`

**Comment by jorshimayor** [comment]
Okay, I will. Thanks

**Comment by zxstim** [comment]
Closing this issue, ready for payout.

**Comment by zxstim** [comment]
Oh please open a BUIDL on dorahacks or this.

https://dorahacks.io/hackathon/kaia-onchain-summer/detail#submission-guidelines

**Comment by jorshimayor** [comment]
Aight. Thanks, I'll do that now.

**Comment by zxstim** [comment]
You need to include this in your BUIDL otherwise we don't know where to pay you

```
----
Acknowledgement: I confirm the below address is my bounty payout address.  
Payout address: [insert your address]
```

**Comment by jorshimayor** [comment]
Oh okay. I'd put it in the BUIDL but I reckon it's in a wrong Description. I'll try it again. Thanks.

**Comment by jorshimayor** [comment]
Also, please are we allowed to post on our personal blog or on twitter as a thread?

**Comment by zxstim** [comment]
absolutely. it would also be nice if you mention about this kaia onchain summer as well.
