### ISSUE TITLE
Proposal: Understanding Kaia's State Transition Model

### ISSUE THREAD

**Issue by Joel-web3** [kaiachain/kaia-dapp-mono#69]
Description
- I'll give a detailed explanation on how the Kaia blockchain state is updated with each block, focusing on the role of the Merkle Patricia Trie and the World State.

Bounty track
- Education

**Comment by zxstim** [comment]
Noted. Try taking a crack at it and revert back

**Comment by Joel-web3** [comment]
GM @zxstim 

I just created a pull request for my proposed write-up (in Markdown format). 

Kindly have a look and let me know your thoughts.

**Comment by Joel-web3** [comment]
There's a link to the flipside dashboard just before the conclusion paragraph where I talked about the performance metrics.

**Comment by zxstim** [comment]
Gonna up this to 400 KLAY for the dashboard

**Comment by Joel-web3** [comment]
Thank you! I just submitted a BUIDL for this proposal on DoraHacks.

**Comment by zxstim** [comment]
Can you create a BUIDL on dorahacks as well?

for reference: https://dorahacks.io/hackathon/kaia-fall-odyssey/detail#submission-guidelines

**Comment by Joel-web3** [comment]
I did. It has been reviewed and is now live.

[](https://dorahacks.io/buidl/15683)

**Comment by zxstim** [comment]
Ah can you add it into the link above. You can submit the BUIDL there.
