### ISSUE TITLE
Proposal: Telegram 2FA for Klaytn Transfers

### ISSUE THREAD

**Issue by tomosaigon** [kaiachain/kaia-dapp-mono#7]
Description
- Add security to your Klaytn hot wallet by depositing Klay into a contract that requires your signer and a second signer from a Telegram bot you register into the contract

Bounty track
- Contribute a Telegram Bot to perform some actions on Klaytn

**Comment by tomosaigon** [comment]
Migrated from https://github.com/klaytn/klaytn-dapp-toolkit/issues/60

Working (locally deployed) with Telegram "@klaypal_bot" account: https://github.com/tomosaigon/klaypal

Deployed to klaytnBaobab AND Klaytn Mainnet Cypress and 0.001337 KLAY safely transferred to 0x3285b..f2694 from UI with klaypal_bot's sig!

![image](https://github.com/kaiachain/kaia-dapp-mono/assets/1016509/f8b1e717-725f-4694-a41f-33039da2e05f)

**Comment by zxstim** [comment]
this looks awesome. Will check later tonight 👍

**Comment by zxstim** [comment]
Great work. Approved for payout 👍

**Comment by zxstim** [comment]
can you open a PR and edit this file with the information of your submission?
https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/submissions.md

you can follow the previous edits
Telegram 2FA for KAIA Transfers - @[your-github-username] | Repos: ...

**Comment by zxstim** [comment]
Closing this Issue and Mark as Done. If you want to keep building on this submission, please open a new issue and propose the new updates.
