### ISSUE TITLE
Proposal: [The KIln: NFT Minter]

### ISSUE THREAD

**Issue by LurkyLunk** [kaiachain/kaia-dapp-mono#72]
Description
- [The Kiln is a simple, decentralized NFT minting platform built specifically for the Klaytn blockchain. It empowers creators and collectors to mint, any image into an NFT.    

[Watch the demo video](https://gateway.pinata.cloud/ipfs/QmXkXArYUrqXVeFX4Ydp38a8JxYD5DnYxizv7RrPJPgCQ8)

🚀 Features 🔗 Multi-Wallet Integration: Seamless connection with Kaikas and MetaMask wallets. 🖼️ User-Friendly Minting: Intuitive interface for uploading media and minting NFTs. ⛽ Real-Time Gas Estimation: Accurate gas fee predictions before minting. 🔒 Role-Based Access Control: Enhanced security with customizable minting permissions. 📊 Supply Management: Set and manage the maximum supply for your NFT collections. 🌐 IPFS Integration: Reliable, decentralized storage for NFT metadata and assets via Pinata.]

Bounty track
- [Contribute a free to use DApp onto mainnet - NFT mint tools]

**Comment by LurkyLunk** [comment]
Does this work? What do i do next?

**Comment by zxstim** [comment]
I like the idea. You would need to improve the UI/UX more for bounty though since the bounty amount is much higher than before.

For submission, you would post here the repositories with the code (frontend and contracts), plus link to your deployed app.

**Comment by kaia-dev-intern** [comment]
Also, highly recommend checking out ERC6551 to add in with your submission. There are some interesting tech with that.

**Comment by LurkyLunk** [comment]
thanks, @zxstim will do. Also, thanks for the suggestion @kaia-dev-intern i will check it out.

**Comment by LurkyLunk** [comment]
does this look better? if not can you please give me a lil more detail about what i need to change to make it more appealing 
@zxstim https://gateway.pinata.cloud/ipfs/QmeAxtTivHnQxecoimX6DPsfLbnQVScDzMU3xSeEr8cbiw

**Comment by zxstim** [comment]
Ok. Imma be fair on this since that viral pump dot fun also looks like shit. Can you submit your code repos and link to your deployed app?

**Comment by LurkyLunk** [comment]
https://klaytn-nft-minter-asa2lckpd-lurkylunks-projects.vercel.app/

https://github.com/Masxon-Studios/THEKILN

im still working out a few deployment issues though.

**Comment by zxstim** [comment]
Yea take your time. I will be ok if the UX is good. Meaning it's easy to use the functionalities, regardless of the UI design.

**Comment by LurkyLunk** [comment]
https://klaytn-nft-minter-2pn54opqd-lurkylunks-projects.vercel.app/

contracts: 
https://github.com/Masxon-Studios/simple-klaytn-nft

frontend:
https://github.com/Masxon-Studios/klaytn-nft-minter

Sorry i got swamped at work. I split the repository in two. Frontend and Contracts. I plan on doing more to it as i go along. lmk of any other cool ideas you have that i can knock out after the community badge bot. I should be done with it soon. Also, can i just keep adding the functionality to my ecosystem or should i create an entirely new dapp each time. I have more ideas that i will submitting soon. Should i post my wallet address here or?

**Comment by zxstim** [comment]
@LurkyLunk follow the instruction here to receive the payout. I will check your work and revert back soon

https://dorahacks.io/hackathon/kaia-onchain-summer/detail#submission-guidelines

**Comment by LurkyLunk** [comment]
This may be a dumb question, but do you have Kaikas Wallet installed in your browser. Can you sign-out of your kaikas wallet and refresh the page and tell me what happens.

**Comment by LurkyLunk** [comment]
Let me know if it's working for you now.

**Comment by zxstim** [comment]
Lol. I would suggest you to use [RainbowKit](https://www.rainbowkit.com/). I'm a power user so kaikas doesn't fit my day-to-day nor my development work.

Best not to assume what your users have because people have many different setups. Many are on mobile as well.

**Comment by LurkyLunk** [comment]
frontend:
https://github.com/Masxon-Studios/THEKILN

contracts:
https://github.com/Masxon-Studios/simple-klaytn-nft

url:
https://kiln-tau.vercel.app/

https://gateway.pinata.cloud/ipfs/QmQ6W6FEMKJrnc9KQVdtvjNDHBMwha372NVwEwZJeTevSr
Sorry about all the hassle. Thanks for all the advice. Im going to get the Discord bot finished now.

**Comment by zxstim** [comment]
Cool. Give me a few days to check on this.

**Comment by zxstim** [comment]
Hmm... I think there are some issues with your smart contract. You called the `mintNFT` function but no NFT minted out. Transaction went to a normal address instead of a contract.

**Comment by zxstim** [comment]
Also, please include a testnet version as well before you go to mainnet. Testnet should work before mainnet deployment.

**Comment by LurkyLunk** [comment]
Are you referring to the repositories or the dapp itself?

**Comment by LurkyLunk** [comment]
Somehow some of my work got reverted when deploying,  I fixed it. Thank you.

**Comment by LurkyLunk** [comment]
Please if this works for you send payment ASAP I really need it. it's kinda an emergency at this point.

**Comment by zxstim** [comment]
![image](https://github.com/user-attachments/assets/9196b605-4bfb-4fdd-8e63-59a47ffd2835)

this is what i got. Can't mint. Happy to bring up the bounty the more polished the dapp. Current bounty payout is `1500 KLAY` to `2500 KLAY`

just a note, Kaia Onchain Summer will end but a new campaign will start immediately after so no rush.

**Comment by LurkyLunk** [comment]
Ok thank you and I'm not sure why it's doing this but I will fix it.

**Comment by LurkyLunk** [comment]
Ok try it now it should be working for you, im sorry about that. Im going to add a wallet where you can view them and a few other things if you have any suggestions of how to make it more polished please lmk.

**Comment by LurkyLunk** [comment]
https://kiln-tau.vercel.app/ 

Ok check it out now and tell  me what you think.

**Comment by LurkyLunk** [comment]
Not to be a hassle but the reason it is so urgent is I need it to pay bills and to take care of my 5 year old son. So if this works for you please send payment ASAP.

**Comment by LurkyLunk** [comment]
Hello?

**Comment by LurkyLunk** [comment]
Hey man I have a 5 year old to take care of and bills due. Can I get paid today? Check it out everything is done.

**Comment by LurkyLunk** [comment]
Hello?

**Comment by zxstim** [comment]
Somewhat rough around the edges but I can mint the NFT now. Approved for `1500 KLAY` payout.

Highly encourage you to keep building this up with more feature sets, different NFT types, etc.

Grow it into an easily customizable NFT launch tool.

**Comment by zxstim** [comment]
Closing this issue ready for payout

**Comment by LurkyLunk** [comment]
I could do more to it and more dapps if you would respond in a reasonable timeframe and if you want to keep paying me otherwise I would have to add some kind of fees also could respond to the discord bot thread so I can finish it up also.

**Comment by zxstim** [comment]
I am happy to keep paying you as you make more upgrades (substantial improvement). Also, the free DApp is an old rule, you can charge users how ever much you want.

Ok. Regarding responding within a reasonable timeframe, I do need time to review your codebase, try things out. At the same time, I also have others submitting as well. And other works/research. Then once in a while i go on short leave. Just keep tagging my handle for attention since github is bad at notification.

**Comment by LurkyLunk** [comment]
Ok thank you for the clarification and understanding I know your busy. I'll continue to make improvements

**Comment by zxstim** [comment]
Add yourself to the hall of fame here so others would know and check out your minter

https://github.com/kaiachain/kaia-dapp-mono/blob/main/bounty/hall-of-fame.md

**Comment by LurkyLunk** [comment]
Ok i create a PR for the hall for the hall of fame,
