### ISSUE TITLE
Proposal: Deep Dive Into The Consensus Mechanism of Kaia Chain 

### ISSUE THREAD

**Issue by mawutory** [kaiachain/kaia-dapp-mono#79]
Description
- This submission will be a blog post that breaks down the version of the Istanbul Byzantine Fault Tolerance consensus used in Kaia. The post will do a step-by-step deep dive as to how consensus is achieved. The goal is to explain how Kaia's consensus works to researchers and blockchain enthusiasts in general.

Bounty track
- Education

**Comment by zxstim** [comment]
Yes. Make sure to include references if any. Go deep with diagrams for bonus

**Comment by mawutory** [comment]
@zxstim how does this look?

https://dev.to/polymawutor/deep-dive-into-the-consensus-mechanism-of-kaia-chain-11j7

**Comment by zxstim** [comment]
Looks good. Approved for `400 KLAY` payout.

**Comment by zxstim** [comment]
Can you open a PR here and add your article in as a `.md` file?

https://github.com/kaiachain/kaia-dapp-mono/tree/main/learn

make the file name as `your-title-with-dashes.md`

**Comment by zxstim** [comment]
Oh please open a BUIDL on dorahacks or this.

https://dorahacks.io/hackathon/kaia-onchain-summer/detail#submission-guidelines

**Comment by mawutory** [comment]
@zxstim Thanks for the review, sir. Please I've already submitted a BUIDL at https://dorahacks.io/buidl/14771

**Comment by zxstim** [comment]
Ok. Closing this Issue ready for payout.

**Comment by mawutory** [comment]
Thank you and God bless you, the bounty is very much appreciated!
