### ISSUE TITLE
Proposal: The News Update Bot of Telegram

### ISSUE THREAD

**Issue by binaaaaaaaaa** [kaiachain/kaia-dapp-mono#8]
Description

I created a bot to update daily news for users.
Every day when you submit /news, the bot will send you back the latest blockchain news of the day.

**Comment by zxstim** [comment]
Requirements for this bounty:
- Must use [CryptoPanic API](https://cryptopanic.com/developers/api/).
- A telegram bot that takes full use of CryptoPanic API various filters, regions, currencies, etc.
- Well structured codebase

You can submit v0 first and i will give you some feedbacks to proceed further

**Comment by binaaaaaaaaa** [comment]
I have replaced Python with TypeScript to facilitate easier updates and enhance user convenience.
Additionally, I have integrated an API to create a more flexible, fast, and efficient connection between developers and the website.
This new version will allow you to choose your preferred language.
You can also select keywords so that the Telegram bot can deliver news that matches your requirements.
https://github.com/binaaaaaaaaa/Kaia-Telegram-bot-news

**Comment by zxstim** [comment]
Much better. Please work on an improved implementation of this with a dedicated SDK for CryptoPanic API and make use of some sentiment analysis.

This news bot can work well with a portfolio tracker bot.

Anyway, approved for `700 KLAY` payout.

**Comment by zxstim** [comment]
Payout is completed so closing this issue. Open new issue if you want to submit an update.
