### ISSUE TITLE
Proposal: KAIA Tokenomics Explained

### ISSUE THREAD

**Issue by polymawutor** [kaiachain/kaia-dapp-mono#80]
Description
- The submission will be a blog post that will explore the utility of the KAIA token, its supply and distribution, major allocations, and most importantly, the token's inflation. 

Bounty track
- Education

**Comment by zxstim** [comment]
Approved to proceed. Bonus if you can build some dashboards on flipsidecrypto.xyz

**Comment by mawutory** [comment]
@zxstim 

Please, I wanted to build a dashboard that tracked the wallets of the KEF, KIF, and the CCOs but I could not find the relevant wallet addresses. I'm happy to build the dash if I'm furnished with the address. 

Here's the current state of the article: https://dev.to/polymawutor/kaia-tokenomics-explained-1dog

I will proceed with submitting a BUIDL and will submit a PR after your approval.

Thank you!

**Comment by zxstim** [comment]
ah. Sorry just saw this. Will check and revert.

**Comment by polymawutor** [comment]
@zxstim any updates on this, sir?

**Comment by zxstim** [comment]
Sorry. Next time, keep tagging my handle every 2, 3 days so GitHub notifies me continuously.

Approved for `500 KLAY` payout.

**Comment by zxstim** [comment]
Closing for payout
