### ISSUE TITLE
Proposal: Pyth Integration Template with simplified docs

### ISSUE THREAD

**Issue by PaulElisha** [kaiachain/kaia-dapp-mono#83]
Description
- A smart contract template showcasing Pyth Integration in a `FundMe` contract that uses Pyth Price Feeds to get the usd value of Klay token. 
- This contract demonstrate the use of the `MockPyth` contract to create a price update calldata.
- An article is linked in the readMe file for education purposes.

Bounty track
- Education.

**Comment by zxstim** [comment]
Approved for `500 KLAY` payout

**Comment by zxstim** [comment]
Closing this issue since the bounty has been paid
