### ISSUE TITLE
Proposal: Wibu Bot - Defi trading bot

### ISSUE THREAD

**Issue by chauanhtuan185** [kaiachain/kaia-dapp-mono#9]
Description
- Create a telegram bot to trade Token on Dex with Mini-app

Bounty track
- [add the name of the bounty track here]

**Comment by zxstim** [comment]
Approved. This would be interesting. A couple notes:
- telegram bot for this case is probably better to be TS based (i.e. telegraf)
- bonus points if you find a way to encrypt my private key/seed phrases locally on server
- repo should be divided well between telegram bot running and the actual trading scripts

**Comment by chauanhtuan185** [comment]
Hello guy , after one month explore 
Hello guy, after a month of exploring I got an mvp and a working bot here is my repo and demo : 
Repo : https://github.com/chauanhtuan185/Kaia-Defi-Trading-Bot
Demo : https://www.youtube.com/shorts/DBW0-8soZ58

**Comment by zxstim** [comment]
Payout is completed so closing this issue. Open new issue if you submit an update.
