### ISSUE TITLE
Proposal: Meet up presentation: Kaia Vietnam at Hung Vuong Technology Vocational School on 09/10/2024

### ISSUE THREAD

**Issue by olym3labs** [kaiachain/kaia-dapp-mono#99]
Description
Join us for a special meetup at Hung Vuong Technology Vocational School to introduce Kaia Vietnam's latest initiatives. Discover cutting-edge technologies, engage with industry experts, and explore new opportunities in tech and innovation. Let's connect, learn, and grow together on 10th September 2024!

Location: https://maps.app.goo.gl/MBjkqVAtaZysDdBq6

**Comment by zxstim** [comment]
Approved for `600 KLAY` bounty

**Comment by zxstim** [comment]
for reference:
https://x.com/zxstim/status/1844196903392772365

**Comment by zxstim** [comment]
Closing for payout
